Include the visual version of Layout L005
selsa-inube/crediboard pull request #10
Opened 2024-04-13 00:03 UTC by novadeveloper14

2024-04-15 16:37 UTC, Andresbl123 approved these changes
Cumple requerimiento

2024-04-16 09:49 UTC, carin91 requested changes

2024-04-16 09:49 UTC, carin91 commented on src/components/layout/BoardSection/styles.ts
> +    $collapse ? "rotate(-90deg)" : "rotate(90deg)"};
The rotation must be adjusted according to the wireframes.
![image](https://github.com/selsa-inube/crediboard/assets/123512032/6025adc2-d364-4450-8f1f-b13073708798)

2024-04-16 09:49 UTC, carin91 commented on src/components/layout/BoardSection/styles.ts
> +  background-color: ${({ theme, $sectionBackground }) =>
The background color must be controlled by the collapse state, according to the wireframes.
![image](https://github.com/selsa-inube/crediboard/assets/123512032/22a5e8f8-4c4b-4ade-b58a-93ec6aee018b)

2024-04-16 09:49 UTC, carin91 commented on src/components/layout/BoardSection/types.ts
> +type SectionOrientation = "horizontal" | "vertical";
Do not mix languages.
Spanish will be used for:
(1) paths
(2) Endpoints or other requirements of the server
(3) configs and information/labels/others presented on the page.

The SectionOrientation type describes a prop of the component, therefore, the options would be defined in english.

2024-04-17 04:41 UTC, novadeveloper14 commented on src/components/layout/BoardSection/styles.ts
> +  background-color: ${({ theme, $sectionBackground }) =>
The background color is not managed with the collapse state, it is simply handled the same as it is handled vertically (according to the wireframes)

![image](https://github.com/selsa-inube/crediboard/assets/87447257/448f93b7-0325-4b45-80b7-137f23e09a71)

2024-04-17 04:47 UTC, novadeveloper14 commented on src/components/layout/BoardSection/types.ts
> +type SectionOrientation = "horizontal" | "vertical";
The words “horizontal” and “vertical” are written the same way in both English and Spanish. Therefore, the SectionOrientation type is interpreted correctly.

2024-04-17 09:58 UTC, merged