At/cb 134 implement inubekit on login pages
selsa-inube/crediboard pull request #113
Opened 2024-08-06 22:16 UTC by Angelbt12

Implement inubekit on login pages
![image](https://github.com/user-attachments/assets/583cb0ea-8b95-413b-a1ff-9b0069716ac7)
Adjust the Login Pages to change the design-system components to design-system-web (inubekit) components

2024-08-08 16:36 UTC, diegoAndres01 requested changes

2024-08-08 16:36 UTC, diegoAndres01 commented on src/pages/login/outlets/CheckingCredentials/interface.tsx
>        </Stack>
This semicolon should be removed

2024-08-08 18:57 UTC, Angelbt12 commented on src/pages/login/outlets/CheckingCredentials/interface.tsx
>        </Stack>
ok

2024-08-08 20:26 UTC, diegoAndres01 approved these changes

2024-08-14 03:09 UTC, carin91 approved these changes

2024-08-14 03:09 UTC, carin91 commented on src/pages/login/outlets/Clients/styles.ts
> +      `${theme? "24px" : "24px"}`};
Delete the theme validation and pass directly the 24px

2024-08-14 03:09 UTC, carin91 commented on src/pages/login/outlets/Clients/styles.ts
> +    `${theme? "16px" : "16px"} ${
Delete the theme validation and pass directly the 16px

2024-08-14 03:09 UTC, carin91 commented on src/pages/login/outlets/Clients/styles.ts
> +      theme? "0px" : "0px"
Delete the theme validation and pass directly the 0px

2024-08-14 12:13 UTC, Angelbt12 commented on src/pages/login/outlets/Clients/styles.ts
> +      `${theme? "24px" : "24px"}`};
ok

2024-08-14 12:13 UTC, Angelbt12 commented on src/pages/login/outlets/Clients/styles.ts
> +    `${theme? "16px" : "16px"} ${
ok

2024-08-14 12:20 UTC, Angelbt12 commented on src/pages/login/outlets/Clients/styles.ts
> +      theme? "0px" : "0px"
ok

2024-08-14 20:25 UTC, merged