At/cb 138 including flags
selsa-inube/crediboard pull request #115
Opened 2024-08-08 18:57 UTC by Angelbt12

Include the Flag on every pending button in the extended card. (Enviar, editar asesor comercial, entre otros …)
![image](https://github.com/user-attachments/assets/1413fd8e-a055-4324-b432-407c46756c0a)

2024-08-12 20:06 UTC, diegoAndres01 requested changes

2024-08-12 20:06 UTC, diegoAndres01 commented on src/pages/board/outlets/financialReporting/ToDo/index.tsx
The icon size is small compared to the Jira card image

![image](https://github.com/user-attachments/assets/8bd162b8-506d-4c7f-b821-27d77a0185b7)

2024-08-13 16:28 UTC, diegoAndres01 approved these changes

2024-08-14 03:27 UTC, carin91 approved these changes

2024-08-15 12:15 UTC, merged