at/cb-147-create-db-mock-for-payment-capacity
selsa-inube/crediboard pull request #118
Opened 2024-08-13 12:52 UTC by Angelbt12

Create DB mock for "payment capacity"
![image](https://github.com/user-attachments/assets/57aa3b20-08e2-4f93-8c85-ebea3d278a4f)

2024-08-13 14:02 UTC, Andresbl123 approved these changes
cumple requerimiento

2024-08-14 03:43 UTC, carin91 requested changes

2024-08-14 03:43 UTC, carin91 commented on src/mocks/creditProfileInfo/paymentCapacity.mock.ts
> +      percentage_used: 60,
This is not necessary, should be calculated based con the available_percentage (used_percentage = 1 - available_percentage).

2024-08-14 03:43 UTC, carin91 commented on src/mocks/creditProfileInfo/paymentCapacity.mock.ts
> +export const payment_capacityInfo = [
The task considers rendering the information on every fieldset based on the mock.
![image](https://github.com/user-attachments/assets/a93f7662-2406-4104-afb6-2155ae270ef2)
As an example, you could review the code which controls the risk scoring rendering
![image](https://github.com/user-attachments/assets/979c5186-6941-424e-a24d-c2d7874de762)

2024-08-14 15:24 UTC, Angelbt12 commented on src/mocks/creditProfileInfo/paymentCapacity.mock.ts
> +      percentage_used: 60,
ok

2024-08-23 19:10 UTC, carin91 commented on src/mocks/creditProfileInfo/paymentCapacity.mock.ts
> +export const payment_capacityInfo = [
This activity is still pending

2024-09-04 20:15 UTC, carin91 approved these changes

2024-09-04 21:09 UTC, merged