At/cb 148 create a mock for uncovered portfolio
selsa-inube/crediboard pull request #119
Opened 2024-08-13 19:43 UTC by Angelbt12

Create a mock for "uncovered portfolio"
![image](https://github.com/user-attachments/assets/fe61b094-3110-4be4-aa05-538b3148f728)

2024-08-13 20:49 UTC, diegoAndres01 approved these changes

2024-08-14 03:40 UTC, carin91 requested changes

2024-08-14 03:40 UTC, carin91 commented on src/mocks/creditProfileInfo/creditBehavior.mock.ts
> +    Credit_behavior: {
all of the fields should be in lowercase

2024-08-14 03:40 UTC, carin91 commented on src/mocks/creditProfileInfo/creditBehavior.mock.ts
> +        core_risk_score: 250 ,
The information must include a date.

2024-08-14 03:40 UTC, carin91 commented on src/mocks/creditProfileInfo/creditBehavior.mock.ts
> +export const credit_behaviorInfo = [
The task considers rendering the information on every fieldset based on the mock.
![image](https://github.com/user-attachments/assets/a93f7662-2406-4104-afb6-2155ae270ef2)
As an example, you could review the code which controls the risk scoring rendering
![image](https://github.com/user-attachments/assets/979c5186-6941-424e-a24d-c2d7874de762)

2024-08-14 12:28 UTC, Angelbt12 commented on src/mocks/creditProfileInfo/creditBehavior.mock.ts
> +    Credit_behavior: {
ok

2024-08-14 12:28 UTC, Angelbt12 commented on src/mocks/creditProfileInfo/creditBehavior.mock.ts
> +        core_risk_score: 250 ,
ok

2024-08-16 02:26 UTC, carin91 requested changes

2024-08-16 02:26 UTC, carin91 commented on src/mocks/creditProfileInfo/paymentCapacity.mock.ts
> +export const payment_capacityInfo = [
adjust the spelling to payment_capacity

2024-08-16 02:26 UTC, carin91 commented on src/mocks/creditProfileInfo/creditBehavior.mock.ts
> +        central_risk_scor_date: "ago/31/2023",
adjust the spelling: central_risk_score_date

2024-08-16 02:26 UTC, carin91 commented on src/mocks/creditProfileInfo/creditBehavior.mock.ts
> +export const credit_behaviorInfo = [
This activity is still pending

2024-08-16 12:41 UTC, Angelbt12 commented on src/mocks/creditProfileInfo/creditBehavior.mock.ts
> +        central_risk_scor_date: "ago/31/2023",
ok

2024-08-23 19:20 UTC, carin91 commented on src/mocks/creditProfileInfo/creditBehavior.mock.ts
> +export const credit_behaviorInfo = [
This activity is still pending

2024-09-04 20:21 UTC, carin91 approved these changes

2024-09-04 22:16 UTC, merged