At/cb 149 mock the uncovered portfolio
selsa-inube/crediboard pull request #123
Opened 2024-08-14 15:50 UTC by Angelbt12

Mock the "uncovered portfolio"
![image](https://github.com/user-attachments/assets/fc015708-6f37-4cb9-b9fd-31384bff12ea)

2024-08-16 13:31 UTC, Brandonz07 approved these changes

2024-08-23 19:18 UTC, carin91 requested changes

2024-08-23 19:18 UTC, carin91 commented on src/mocks/creditProfileInfo/creditBehavior.mock.ts
> +export const credit_behavior = [
Based on this information you should render the data into the uncovered portfolio fieldset.
![image](https://github.com/user-attachments/assets/c633d5ec-c957-43e0-b586-a1c80f0b0eee)

2024-09-04 20:23 UTC, carin91 approved these changes

2024-09-04 22:18 UTC, merged