Include seven `<Fieldsets />` on p003
selsa-inube/crediboard pull request #13
Opened 2024-04-17 17:11 UTC by Andresbl123

In this PR, the following changes have been made:

1. A new `<FinancialReportingSections />` component has been created that contains the structure and content of the financial reporting sections. This component uses the `<Stack />` component to organise the elements in a column direction and the `<Grid />` component to organise the elements in a grid.

2. The `<Fieldset />` component has been used to encapsulate each financial reporting section. Each `<Fieldset />` contains a title and a description.

3. The Text component has been used to provide content for each `<Fieldset />`.

4. A new `<FinancialReporting />` component has been created that encapsulates the `<FinancialReportingSections />` component within the `<ContainerSections />` component

.

2024-04-18 04:56 UTC, novadeveloper14 requested changes

2024-04-18 04:56 UTC, novadeveloper14 commented on src/pages/home/financialReporting/index.tsx
> +import { Fieldset } from "@src/components/data/Fieldset";
Adjust to the standard for imports in this team:
(1) External components
(space)
(2) Internal components which use aliases
(space)
(3) Internal component without aliases

2024-04-18 19:54 UTC, Andresbl123 commented on src/pages/home/financialReporting/index.tsx
> +import { Fieldset } from "@src/components/data/Fieldset";
resuelto

2024-04-18 22:07 UTC, novadeveloper14 approved these changes

2024-04-19 12:42 UTC, carin91 requested changes

2024-04-19 12:42 UTC, carin91 commented on src/components/data/Fieldset/styles.ts
> +    theme?.color?.stroke?.divider?.regular ||
why do you use the divider block for the border?

2024-04-19 12:42 UTC, carin91 commented on src/pages/home/financialReporting/index.tsx
> +          <Fieldset title={data.title} descriptionTitle={data.descriptionTitle}>
The fieldset is a prop of the children, is not created/defined on the page. So, to define the structure it is ok, however, every new component created would have its fieldset. Don't you think?

2024-04-19 12:42 UTC, carin91 commented on src/pages/home/financialReporting/index.tsx
> +import { Stack, inube, Text, Grid } from "@inube/design-system";
The location of this file should be evaluated, however, remember that the home folder will be deleted (this is included in the cb27)

2024-04-19 12:42 UTC, carin91 commented on src/App.tsx
> +      <Route path="financial-reporting" element={<FinancialReporting />} />
the financial-reporting will be a path of the board, this is ok to verify the rendered page, however, the cb27 includes a different location for this page. We need to evaluate the best location for this page.

2024-04-19 22:23 UTC, Andresbl123 commented on src/pages/home/financialReporting/index.tsx
> +          <Fieldset title={data.title} descriptionTitle={data.descriptionTitle}>
Claro si sr, por ahora esto esta para definir el layout  de la pagina a medida que se ingreses los compontes ya es responsabilidad del mismo mirar como será su contenedor, pero se dejo así para indicar el outlet donde se van a colocar lo que se quiere renderizar según la mock del diseño

2024-04-19 22:23 UTC, Andresbl123 commented on src/components/data/Fieldset/styles.ts
> +    theme?.color?.stroke?.divider?.regular ||
resuelto

2024-04-22 17:03 UTC, Andresbl123 commented on src/pages/home/financialReporting/index.tsx
> +import { Stack, inube, Text, Grid } from "@inube/design-system";
validado

2024-04-22 17:03 UTC, Andresbl123 commented on src/App.tsx
> +      <Route path="financial-reporting" element={<FinancialReporting />} />
validado

2024-04-24 22:31 UTC, merged