cb160 Handling errors: no request-pinned
selsa-inube/crediboard pull request #132
Opened 2024-08-21 14:30 UTC by Brandonz07

If there is no data in the mock, it should not allow anchoring, and should show the user

![image](https://github.com/user-attachments/assets/c0c86566-4b13-42a5-86d7-75853aa9c7df)

![image](https://github.com/user-attachments/assets/85bab19c-c189-4d57-bcd0-1306e5b6bc4b)

2024-08-26 15:27 UTC, Andresbl123 reviewed
Al tratar de realizar el filtro dese el selectcheck se rompe la app
![Grabación-de-pantalla-2024-08-26-101826](https://github.com/user-attachments/assets/cd7f5b6b-e515-4f4d-8fc6-25553656867c)

2024-09-04 15:09 UTC, Andresbl123 commented on src/pages/board/outlets/boardlayout/interface.tsx
> +  useEffect(() => {
realmente este  `useEffect` no deberia ser necesario, un eseEffect se utiliza para sincronizar con un sistema externo, y según esto `pinnedRequests` le llega por props, me sigue pareciendo que este enfoque es errone, y lo que se debe hacer es capturar el error en el fetching de datos, para así poder capturar el error y notificarle al usuario, esto implicaría cambiar varias cosas de las realizadas

2024-09-04 20:33 UTC, carin91 requested changes

2024-09-04 20:33 UTC, carin91 commented on src/pages/board/outlets/boardlayout/interface.tsx
> +  useEffect(() => {
attend this issue

2024-09-09 22:15 UTC, Andresbl123 commented on src/pages/board/outlets/boardlayout/styles.ts
> +const StyledToast = styled.div<IStyledToast>`
tener en cuenta comentario de `[src/pages/board/outlets/boardlayout/interface.tsx](https://github.com/selsa-inube/crediboard/pull/132/files#diff-4bc639532786cc83218f60ebf2a0f8ac2671dd9b355fb191c8b5b9771d414893)` creo que esto se podría utilizar para ajustar a `ErrorAlert`

2024-09-17 19:44 UTC, carin91 approved these changes

2024-09-17 19:44 UTC, carin91 commented on src/pages/board/outlets/boardlayout/interface.tsx
> +                  label="Filtrado por"
relocate this sentence to a config file

2024-09-17 19:44 UTC, carin91 commented on src/pages/board/outlets/boardlayout/interface.tsx
> +                  placeholder="Seleccione una opción"
relocate this sentence to a config file

2024-09-17 19:44 UTC, carin91 commented on src/pages/board/outlets/boardlayout/interface.tsx
> +          </StyledToast>
Are you comfortable with the name? it looks like a bread, why do you use this name?

2024-09-17 19:44 UTC, carin91 commented on src/pages/board/outlets/boardlayout/interface.tsx
> +                  <Text type="label">Ver unicamente los anclados</Text>
relocate this sentence to a config file

2024-09-18 12:13 UTC, merged