cb166 Credit Product component
selsa-inube/crediboard pull request #139
Opened 2024-08-22 21:39 UTC by novadeveloper14

![image](https://github.com/user-attachments/assets/925e5efd-9194-4fc0-8125-694283222fa0)

2024-08-23 17:41 UTC, diegoAndres01 requested changes

2024-08-23 17:41 UTC, diegoAndres01 commented on src/components/cards/CreditProductCard/styles.ts
> +  box-shadow: 0px 4px 8px 3px rgba(9, 30, 66, 0.13);
The box-shadow property is repeated

2024-08-23 17:52 UTC, novadeveloper14 commented on src/components/cards/CreditProductCard/styles.ts
> +  box-shadow: 0px 4px 8px 3px rgba(9, 30, 66, 0.13);
The properties were not the same, it was copied from what was shown in figma, anyway the box-shadow was removed which did not represent a big change in the appearance of the component

2024-08-26 13:13 UTC, diegoAndres01 approved these changes

2024-08-29 11:26 UTC, carin91 approved these changes

2024-08-29 11:26 UTC, carin91 commented on src/components/cards/CreditProductCard/index.tsx
> +    title,
Change the name of this prop to "Line of Credit"

2024-08-29 11:26 UTC, carin91 commented on src/components/cards/CreditProductCard/index.tsx
> +    paymentCycle,
Change the name of this prop to "Schedule" + add the interface based on the next enumerator: 
weekly, 10-day intervals, biweekly, semimonthly, monthly, bimonthly, quarterly, semiannually, annually.

2024-08-29 11:26 UTC, carin91 commented on src/components/cards/CreditProductCard/interface.tsx
> +            Medio de pago
Avoid magical words, relocate this text in a config file

2024-08-29 11:26 UTC, carin91 commented on src/components/cards/CreditProductCard/interface.tsx
> +            Monto del prestamo
Avoid magical words, relocate this text in a config file

2024-08-29 11:26 UTC, carin91 commented on src/components/cards/CreditProductCard/interface.tsx
> +            Tasa de interés
Avoid magical words, relocate this text in a config file

2024-08-29 11:26 UTC, carin91 commented on src/components/cards/CreditProductCard/interface.tsx
> +            Plazo en meses
Avoid magical words, relocate this text in a config file

2024-08-29 11:26 UTC, carin91 commented on src/components/cards/CreditProductCard/interface.tsx
> +            Cuota periodica K+I
Avoid magical words, relocate this text in a config file

2024-08-29 11:26 UTC, carin91 commented on src/components/cards/CreditProductCard/interface.tsx
> +            Ciclo de pagos
Avoid magical words, relocate this text in a config file

2024-08-29 16:13 UTC, merged