cb153 Register every trace on trace mock
selsa-inube/crediboard pull request #140
Opened 2024-08-23 13:21 UTC by Brandonz07

Every button with a flag should produce a trace on the “trace mock”, including: “Rechazar” “anular” “notificar” …

![image](https://github.com/user-attachments/assets/ed9c9768-d1e6-4ada-bb1b-8197f7cfd8aa)

2024-08-26 16:35 UTC, Andresbl123 commented on src/pages/board/outlets/financialReporting/Requirements/index.tsx
> +  const { id } = useParams();
Esto se puede pasar mejor como props, mejor desde el padre es decir desde `<FinancialReporting />`

2024-09-02 14:28 UTC, Andresbl123 approved these changes
cumple requerimiento

2024-09-05 08:25 UTC, carin91 requested changes

2024-09-05 08:25 UTC, carin91 commented on src/pages/board/outlets/financialReporting/Requirements/index.tsx
> +        trace_id: crypto.randomUUID(),
The trace_id should not be given by the frontend; this is a backend work. Therefore, the trace_id should be created automatically by the mock and not generated by the trace registration

2024-09-05 08:25 UTC, carin91 commented on src/pages/board/outlets/financialReporting/Requirements/index.tsx
> +        trace_type: "novelty_document",
The trace_type is executed_task

Include the enumerator of the trace_type into the services/types
trace_type: novelty, executed_task, novelty_document, document, message

2024-09-05 08:25 UTC, carin91 commented on src/pages/board/outlets/financialReporting/Requirements/index.tsx
> +        read_novelty: "N",
The read_novelty only applies to novelties (data generated by the client, as a message). Due to that, the read_novelty should be a void string ("") in this case.

2024-09-05 08:25 UTC, carin91 commented on src/pages/board/outlets/financialReporting/Requirements/index.tsx
> +          title: "Exito",
This should be in a config file

2024-09-05 08:25 UTC, carin91 commented on src/pages/board/outlets/financialReporting/Requirements/index.tsx
> +          title: "Aprobación Fallida",
It should be defined in a config file.

2024-09-05 08:25 UTC, carin91 commented on src/pages/board/outlets/financialReporting/config.tsx
> +      read_novelty: "N",
The read_novelty only applies to novelties (data generated by the client, as a message). Due to that, the read_novelty should be a void string ("") in this case.

2024-09-05 08:25 UTC, carin91 commented on src/pages/board/outlets/financialReporting/config.tsx
> +        title: "Anulación Confirmada",
Relocate this information into a config file

2024-09-09 04:35 UTC, Brandonz07 commented on src/pages/board/outlets/financialReporting/Requirements/index.tsx
> +        trace_id: crypto.randomUUID(),
the trace_id is generated by the mock

2024-09-09 04:35 UTC, Brandonz07 commented on src/pages/board/outlets/financialReporting/Requirements/index.tsx
> +        trace_type: "novelty_document",
change trace_type

2024-09-09 04:36 UTC, Brandonz07 commented on src/pages/board/outlets/financialReporting/Requirements/index.tsx
> +        read_novelty: "N",
change read_novelty

2024-09-09 04:36 UTC, Brandonz07 commented on src/pages/board/outlets/financialReporting/Requirements/index.tsx
> +          title: "Exito",
i moved to config

2024-09-09 04:36 UTC, Brandonz07 commented on src/pages/board/outlets/financialReporting/config.tsx
> +        title: "Anulación Confirmada",
It's already in config

2024-09-18 11:00 UTC, carin91 approved these changes

2024-09-18 13:48 UTC, merged