cb172 Refactoring mimc input
selsa-inube/crediboard pull request #143
Opened 2024-08-26 21:37 UTC by Brandonz07

Create component reason for change
Card Jira
https://inube.atlassian.net/browse/CB-172

2024-08-28 14:27 UTC, diegoAndres01 requested changes
When hovering over the options, the color is not visible 

![image](https://github.com/user-attachments/assets/399b4954-3a99-4bae-9dd0-3b14c3a4d6b6)

2024-08-28 22:51 UTC, diegoAndres01 approved these changes

2024-08-31 14:54 UTC, carin91 requested changes

2024-08-31 14:54 UTC, carin91 commented on src/components/inputs/SelectCheck/OptionItem/index.tsx
>    const { id, label, checked = false, onchange } = props;
The component is not working; by resolving the issue the styles do not match the expected styles defined on the mockups.
![image](https://github.com/user-attachments/assets/6716edee-d014-453b-acd2-8580a5c3068c)

To solve the breaking down of the application, i apply the changes proposed by Andres
![image](https://github.com/user-attachments/assets/df849d80-2b85-4f65-8314-db67f1e071d7)

2024-09-05 08:01 UTC, carin91 approved these changes

2024-09-05 20:49 UTC, merged