cb179 Board mobile version
selsa-inube/crediboard pull request #145
Opened 2024-08-27 22:23 UTC by Brandonz07

Adjust the dashboard in the mobile version

![image](https://github.com/user-attachments/assets/c442a4e5-88b0-47aa-bd78-29c32e956ae8)

2024-09-02 17:21 UTC, novadeveloper14 approved these changes

2024-09-05 08:04 UTC, carin91 requested changes

2024-09-05 08:04 UTC, carin91 commented on src/pages/board/outlets/boardlayout/interface.tsx
> +import { useEffect, useRef, useState } from "react";
The select check is not working. Merge https://inube.atlassian.net/browse/CB-172 into main, merge main into cb179, and verify that everything works.

2024-09-18 11:44 UTC, carin91 requested changes

2024-09-18 11:44 UTC, carin91 commented on src/pages/board/outlets/boardlayout/interface.tsx
> +                  <Text type="label">Ver unicamente los anclados</Text>
Relocate this into a config file

2024-09-18 11:44 UTC, carin91 commented on src/pages/board/outlets/boardlayout/interface.tsx
> +            <StyledSearch
After writing a string to search, the search text looks invalid contracting itself, i would block the isExpanded state based on the content or hide the content
![image](https://github.com/user-attachments/assets/2b5ff6c7-ae00-4e5c-b8b3-470f1b7910c1)

2024-09-18 11:44 UTC, carin91 commented on src/pages/board/outlets/boardlayout/interface.tsx
> +            return (
This return is required? avoid a return into a return, avoid multiple returns for 1 react component. I would try to delete the return in 207 and verify its operation

2024-09-18 11:44 UTC, carin91 commented on src/pages/board/outlets/boardlayout/interface.tsx
> +              <BoardSection
Adjust the components accordingly to the wireframes, this task includes the adjustment of the board section considering that it is not centered in the mobile version.

![image](https://github.com/user-attachments/assets/deeab201-116e-4f93-9f89-519805081833)

2024-09-20 09:31 UTC, carin91 approved these changes

2024-09-20 09:31 UTC, merged