cb164 Error handling: `risk-scoring`
selsa-inube/crediboard pull request #146
Opened 2024-08-27 23:51 UTC by Andresbl123

This task includes:

(1) Creating additional risk-scoring data on the mock.

(2) Loading the data presented in risk-scoring based on the mock.

(3) Proposing the error handling for the risk-scoring card.

2024-09-03 05:56 UTC, novadeveloper14 requested changes
solve conflicts

2024-09-03 05:56 UTC, novadeveloper14 commented on src/pages/board/outlets/creditProfileInfo/index.tsx
> +import { getById, getDataById } from "@mocks/utils/dataMock.service";
The function “getDataByID” and “getByID” are the same Refactor the index.tsx to use only the getByID.

2024-09-03 05:56 UTC, novadeveloper14 commented on src/pages/board/outlets/creditProfileInfo/RiskScoring/index.tsx
Some requests when entering the credit profile are being bug:

![image](https://github.com/user-attachments/assets/51aa7979-71d7-4f8b-aec0-5d33d90e4888)

2024-09-04 17:31 UTC, Andresbl123 commented on src/pages/board/outlets/creditProfileInfo/index.tsx
> +import { getById, getDataById } from "@mocks/utils/dataMock.service";
Ambas funciones tienen objetivos similares pero están diseñadas para diferentes  enfoques de búsqueda de datos.
**getById** está diseñado para encontrar un solo elemento (el primero que coincida) basado en un identificador numérico (aunque acepta un `string` como identificador, lo convierte a número).
**getDataById** filtra y devuelve un array de elementos que coinciden con el identificador proporcionado, `string`,

2024-09-04 17:39 UTC, Andresbl123 commented on src/pages/board/outlets/creditProfileInfo/RiskScoring/index.tsx
resolve

2024-09-05 19:00 UTC, novadeveloper14 approved these changes

2024-09-06 01:55 UTC, carin91 approved these changes

2024-09-06 16:32 UTC, merged