CB 183 Adjust the prospect on crediboard
selsa-inube/crediboard pull request #150
Opened 2024-08-31 17:50 UTC by diegoAndres01

CB 183 Adjust the prospect on crediboard
[Card Jira](https://inube.atlassian.net/browse/CB-183)

2024-09-03 06:36 UTC, novadeveloper14 requested changes
solve conflicts with main

2024-09-03 06:36 UTC, novadeveloper14 commented on src/pages/board/outlets/financialReporting/index.tsx
The PDF creation parameters must be validated and adjusted. This should take into account the new structure of the data presentation.

![image](https://github.com/user-attachments/assets/bd9ace6f-965f-40a9-9861-78a9094bfab8)

2024-09-03 06:36 UTC, novadeveloper14 commented on src/pages/board/outlets/financialReporting/CommercialManagement/config/config.tsx
> +export const entriesCommercialManagementCard = [
Currently in main in mocks in the following route. We already have the mocks that represent the information that should be displayed on this screen. (only for the information on the prospect cards) let's use the get() of dataMock.service.ts so that through the prospect id the data is obtained and through the key called credit_request_id we show the independent information of each request

Taking this into account we should eliminate this information that you mocked from this file

![image](https://github.com/user-attachments/assets/30e6be65-7074-4d6f-b007-e77882c4fffb)

2024-09-03 06:36 UTC, novadeveloper14 commented on src/pages/board/outlets/financialReporting/CommercialManagement/CardCommercialManagement.tsx
> +      <StyledCardsCredit>
Let's move the scroll to the bottom of the cards without including the SummaryProspect

![image](https://github.com/user-attachments/assets/35f76040-82c1-4ed7-bd93-ab67e240bdd4)

2024-09-03 06:36 UTC, novadeveloper14 commented on src/pages/board/outlets/financialReporting/CommercialManagement/CardCommercialManagement.tsx
> +      <StyledSumaryPropect>
It should occupy 100% of the container according to figma's designs.
figma
![image](https://github.com/user-attachments/assets/692e6a05-3737-4930-b5dd-e575f57bfd64)
dev
![image](https://github.com/user-attachments/assets/c9660e5f-1d74-4733-93b3-f83cd5e439db)

2024-09-03 06:36 UTC, novadeveloper14 commented on src/pages/board/outlets/financialReporting/CommercialManagement/CardCommercialManagement.tsx
> +          <SummaryProspect
Also the background color and box-shadows of the components SummaryProspects is not the same as the designs. The background color of SummaryProspects should be the same as the CreditProductCard. Let's adjust this in this task.

2024-09-03 06:36 UTC, novadeveloper14 commented on src/pages/board/outlets/financialReporting/CommercialManagement/index.tsx
Let's refactor the component to use inubekit's stack and text

2024-09-03 06:36 UTC, novadeveloper14 commented on src/pages/board/outlets/financialReporting/CommercialManagement/CardCommercialManagement.tsx
> +import SummaryProspect from "@components/inputs/SummaryOnProspect";
The import and export of this component is wrong. Internally it should be export { SummaryProspect } and not default SummaryProspect so the import should be import { SummaryProspect } from "@components/inputs/SummaryOnProspect"; with the {}

2024-09-03 06:36 UTC, novadeveloper14 commented on src/pages/board/outlets/financialReporting/CommercialManagement/styles.tsx
> +const StyledCardsCredit = styled.div`
This component could be a Stack

2024-09-03 06:36 UTC, novadeveloper14 commented on src/pages/board/outlets/financialReporting/CommercialManagement/styles.tsx
> +const StyledSumaryPropect = styled.div`
This component could be a Stack

2024-09-03 22:10 UTC, diegoAndres01 commented on src/pages/board/outlets/financialReporting/CommercialManagement/CardCommercialManagement.tsx
> +      <StyledSumaryPropect>
Reviewing the SummaryProspect component, I verify that it has the corresponding measurements with respect to the figma. When trying to implement that all adjustments are according to the figma image sent, it is misaligned.

![image](https://github.com/user-attachments/assets/e05bf671-9d22-4e47-968f-bd42efcb566c)

2024-09-04 07:34 UTC, novadeveloper14 requested changes
The person who reviews the pull request is the one who should resolve the comments made to verify the operation when the developer has solved it.

2024-09-04 07:34 UTC, novadeveloper14 commented on src/components/inputs/SummaryOnProspect/styles.ts
> +  background-color: #FFFFFF;
Let's remember to always use the color tokens from "@inubekit/foundations" as suggested in the review. The same background color as CreditProductCard should be used in the styles.ts. The background color is obtained as follows:

```
import { inube } from "@inubekit/foundations";

background-color: ${({ theme }) =>
theme?.palette?.neutral?.N0 || inube.palette.neutral.N0};
```

(I recommend checking this library to see what types of tokens we can use when creating components and in which case they should be used depending on their token)

2024-09-04 07:34 UTC, novadeveloper14 commented on src/components/inputs/SummaryOnProspect/styles.ts
> +  border: 1px solid var(--Neutral-color-palette-neutral-N30, #EBECF0);
use tokens

2024-09-04 07:34 UTC, novadeveloper14 commented on src/components/inputs/SummaryOnProspect/styles.ts
> +  box-shadow: 0px 1px 3px 0px #091E4221;
use tokens

2024-09-04 07:34 UTC, novadeveloper14 commented on src/pages/board/outlets/financialReporting/CommercialManagement/CardCommercialManagement.tsx
> +            setProspectCredt(propectsCredit);
There is a spelling mistake

2024-09-04 07:34 UTC, novadeveloper14 commented on src/pages/board/outlets/financialReporting/CommercialManagement/CardCommercialManagement.tsx
> +import { ProspectsResponse, CreditProduct } from "@src/services/types";
use the alias directly:

"@services/types"

2024-09-04 07:34 UTC, novadeveloper14 commented on src/pages/board/outlets/financialReporting/CommercialManagement/index.tsx
Stack in inubekit no longer receives this type of values. 

`<Stack margin="s050 s0">`

use (inube.spacing) or pass the values ​​in pixels directly . Check this in the entire component.

![Imagen de WhatsApp 2024-06-06 a las 11 44 42_e3685ece](https://github.com/user-attachments/assets/fa259c87-7ee7-4c68-9732-b423ee9d0df4)

2024-09-04 07:37 UTC, novadeveloper14 commented on src/components/inputs/SummaryOnProspect/index.tsx
> +const parseCunstomFormat = (amount: string) => {
I think this is a function that could be useful in other places in the application, let's move it to the utils folder src\utils\formatData\currency.ts and import it here

2024-09-04 13:28 UTC, diegoAndres01 commented on src/components/inputs/SummaryOnProspect/styles.ts
> +  background-color: #FFFFFF;
Resolved

2024-09-04 13:31 UTC, diegoAndres01 commented on src/pages/board/outlets/financialReporting/CommercialManagement/CardCommercialManagement.tsx
> +import { ProspectsResponse, CreditProduct } from "@src/services/types";
Resolved

2024-09-04 13:33 UTC, diegoAndres01 commented on src/components/inputs/SummaryOnProspect/index.tsx
> +const parseCunstomFormat = (amount: string) => {
Resolved

2024-09-04 14:09 UTC, diegoAndres01 commented on src/components/inputs/SummaryOnProspect/styles.ts
> +  border: 1px solid var(--Neutral-color-palette-neutral-N30, #EBECF0);
Resolved

2024-09-04 14:09 UTC, diegoAndres01 commented on src/components/inputs/SummaryOnProspect/styles.ts
> +  box-shadow: 0px 1px 3px 0px #091E4221;
Resolved

2024-09-04 14:17 UTC, diegoAndres01 commented on src/pages/board/outlets/financialReporting/CommercialManagement/CardCommercialManagement.tsx
> +            setProspectCredt(propectsCredit);
Resolved

2024-09-04 14:21 UTC, diegoAndres01 commented on src/pages/board/outlets/financialReporting/CommercialManagement/index.tsx
When changing the values ​​as mentioned, it does not work because inubekit leaves the values ​​as they are sent, there is no transformation.

![image](https://github.com/user-attachments/assets/bbe24d2b-e069-4519-9008-2616981b8b5c)

2024-09-04 14:21 UTC, diegoAndres01 commented on src/components/inputs/SummaryOnProspect/index.tsx
> +const parseCunstomFormat = (amount: string) => {
Resolved

2024-09-04 15:34 UTC, novadeveloper14 commented on src/pages/board/outlets/financialReporting/CommercialManagement/index.tsx
Stack en inubekit ya no acepta este tipo de valores: <Stack margin="s050 s0"> (de esta manera esta en el documento actualmente)

Utilice (inube.spacing) o pase los valores de los píxeles directamente. Verifique esto en todo el componente.

modificación:

<Stack margin="4px 0px"> o <Stack margin=`${inube.spacing.s050} ${inube.spacing.s0}>`

2024-09-04 15:43 UTC, novadeveloper14 requested changes

2024-09-04 15:43 UTC, novadeveloper14 commented on src/pages/board/outlets/financialReporting/CommercialManagement/CardCommercialManagement.tsx
> +            setProspectiveCredit(propectsCredit);
let's call it setProspectCredit the spelling error is in the const (propectsCredit) it should be called (prospectsCredit)

2024-09-04 15:54 UTC, diegoAndres01 commented on src/pages/board/outlets/financialReporting/CommercialManagement/CardCommercialManagement.tsx
> +            setProspectiveCredit(propectsCredit);
Resolved

2024-09-04 15:54 UTC, diegoAndres01 commented on src/pages/board/outlets/financialReporting/CommercialManagement/index.tsx
ok

2024-09-04 15:56 UTC, novadeveloper14 requested changes

2024-09-04 15:56 UTC, novadeveloper14 commented on src/pages/board/outlets/financialReporting/CommercialManagement/index.tsx
> +              <Stack margin={ `${inube.spacing.s600} ${inube.spacing.s0}` }>
You put a lot of spacing, it should be s050 as it was before, not s600

![image](https://github.com/user-attachments/assets/228cb83b-9cd6-4b29-8171-2961146138e4)

2024-09-04 15:58 UTC, novadeveloper14 approved these changes

2024-09-04 16:03 UTC, novadeveloper14 requested changes

2024-09-04 16:03 UTC, novadeveloper14 commented on src/pages/board/outlets/financialReporting/CommercialManagement/CardCommercialManagement.tsx
> +            const propectsCredit = prospects.value
const (propectsCredit) it should be called (prospectsCredit)

2024-09-04 16:31 UTC, diegoAndres01 commented on src/components/inputs/SummaryOnProspect/index.tsx
> +const parseCunstomFormat = (amount: string) => {
Resolved

2024-09-04 16:31 UTC, diegoAndres01 commented on src/pages/board/outlets/financialReporting/CommercialManagement/CardCommercialManagement.tsx
> +            setProspectiveCredit(propectsCredit);
Resolved

2024-09-04 16:32 UTC, novadeveloper14 approved these changes

2024-09-04 16:32 UTC, diegoAndres01 commented on src/pages/board/outlets/financialReporting/CommercialManagement/index.tsx
> +              <Stack margin={ `${inube.spacing.s600} ${inube.spacing.s0}` }>
Resolved

2024-09-04 16:32 UTC, diegoAndres01 commented on src/pages/board/outlets/financialReporting/CommercialManagement/CardCommercialManagement.tsx
> +            const propectsCredit = prospects.value
Resolved

2024-09-05 08:45 UTC, carin91 requested changes

2024-09-05 08:45 UTC, carin91 commented on src/components/inputs/SummaryOnProspect/index.tsx
> +            margin={inube.spacing.s050}
Refactor avoiding the inube spacing

2024-09-05 08:45 UTC, carin91 commented on src/components/inputs/SummaryOnProspect/styles.ts
> +    inubeDesign.color.stroke.divider.regular};
Adjust it with the token schema in inube from inubekit

2024-09-05 08:45 UTC, carin91 commented on src/components/inputs/SummaryOnProspect/styles.ts
> +  gap: ${inubeDesign.spacing.s800};
avoid inubeDesign

2024-09-05 08:45 UTC, carin91 commented on src/pages/board/outlets/financialReporting/CommercialManagement/index.tsx
> +import { inube, useMediaQuery } from "@inube/design-system";
Use inube and media query from inubekit

2024-09-05 08:45 UTC, carin91 commented on src/pages/board/outlets/financialReporting/CommercialManagement/index.tsx
> +                  Agregar producto
Verify the mockup, you have an extraspace at the beginning of the button content. It could be adjusted without affecting the inubekit? if not, talk with Sergio to adjust the mockup
![image](https://github.com/user-attachments/assets/08fb0b51-92b1-4166-8f2d-dbdac22295b3)
![image](https://github.com/user-attachments/assets/65801b6f-839a-4205-a1b7-903c7ea8c29a)

2024-09-05 08:45 UTC, carin91 commented on src/pages/board/outlets/financialReporting/CommercialManagement/index.tsx
>  import { useState } from "react";
Your deliverable lacks the dropdown
![image](https://github.com/user-attachments/assets/8f4ca95c-83e4-480d-b9a9-55b65c8edd19)
Notice that the mockups have some cases with 3 options (without extraordinary installments) and some cases with 4 options (including extraordinary installments), this behavior will be adjusted in a future issue.

2024-09-05 08:45 UTC, carin91 commented on src/pages/board/outlets/financialReporting/CommercialManagement/styles.tsx
> +  padding: ${inube.spacing.s050};
Avoid the inube tokens from the deprecated design system

2024-09-06 20:39 UTC, diegoAndres01 commented on src/components/inputs/SummaryOnProspect/index.tsx
> +            margin={inube.spacing.s050}
resolved

2024-09-06 20:39 UTC, diegoAndres01 commented on src/components/inputs/SummaryOnProspect/index.tsx
> +import { inube } from "@inube/design-system";
resolved

2024-09-06 20:40 UTC, diegoAndres01 commented on src/components/inputs/SummaryOnProspect/styles.ts
> +import { inube as inubeDesign } from "@inube/design-system";
resolved

2024-09-06 20:40 UTC, diegoAndres01 commented on src/components/inputs/SummaryOnProspect/styles.ts
> +    $showIcon ? inubeDesign.spacing.s200 : inubeDesign.spacing.s800};
Resolved

2024-09-06 20:42 UTC, diegoAndres01 commented on src/components/inputs/SummaryOnProspect/styles.ts
> +  gap: ${inubeDesign.spacing.s800};
Resolved

2024-09-06 20:45 UTC, diegoAndres01 commented on src/pages/board/outlets/financialReporting/CommercialManagement/CardCommercialManagement.tsx
> +import { inube } from "@inube/design-system";
Resolved

2024-09-06 20:45 UTC, diegoAndres01 commented on src/pages/board/outlets/financialReporting/CommercialManagement/CardCommercialManagement.tsx
> +      <Stack gap={inube.spacing.s300} margin={ `${inube.spacing.s450} ${inube.spacing.s0} ${inube.spacing.s100} ${inube.spacing.s0}` } padding={ `${inube.spacing.s0} ${inube.spacing.s100}` } justifyC
Resolved

2024-09-06 20:53 UTC, diegoAndres01 commented on src/pages/board/outlets/financialReporting/CommercialManagement/index.tsx
> +import { inube, useMediaQuery } from "@inube/design-system";
Resolved

2024-09-06 20:55 UTC, diegoAndres01 commented on src/pages/board/outlets/financialReporting/CommercialManagement/styles.tsx
> +  padding: ${inube.spacing.s050};
Resolved

2024-09-08 23:46 UTC, diegoAndres01 commented on src/pages/board/outlets/financialReporting/CommercialManagement/index.tsx
> +                  Agregar producto
Resolved

2024-09-08 23:47 UTC, diegoAndres01 commented on src/pages/board/outlets/financialReporting/CommercialManagement/index.tsx
>  import { useState } from "react";
resolved

2024-09-18 11:03 UTC, carin91 approved these changes

2024-09-18 11:03 UTC, merged