At/cb 182 handling errors payroll discount authorization
selsa-inube/crediboard pull request #153
Opened 2024-09-02 21:01 UTC by Angelbt12

handling errors: payroll-discount-authorization
f the application cannot reach the payroll discount authorization service this information should be passed to the user.

Current behavior: By deleting the payroll discount authorization mock, it looks like there aren’t documents. However, there are documents that aren’t loaded.

Expected behavior: If the service is late, the frontend application should render skeletons with the structure of messages, representing that the application is looking for information.

If the service presented an error, there should render the “information not found” component

Add to the previous activities, you should configure the behavior for the error alert as the current behavior for the trace mock

![image](https://github.com/user-attachments/assets/bb6aefe6-f758-4982-96d0-f8a899a9bc2e)
https://inube.atlassian.net/jira/software/projects/CB/boards/20?selectedIssue=CB-182

2024-09-03 14:18 UTC, diegoAndres01 requested changes

2024-09-04 12:26 UTC, Angelbt12 commented on src/components/layout/UnfoundData/index.tsx
> +  onRetry?: () => void;
ok

2024-09-04 12:31 UTC, Angelbt12 commented on src/pages/board/outlets/financialReporting/PromissoryNotes/index.tsx
> +                widthTd: !isMobile ? "100" : "23%",
ok

2024-09-04 12:35 UTC, Angelbt12 commented on src/components/layout/UnfoundData/index.tsx
> +      margin="s300"
ok

2024-09-04 12:38 UTC, Angelbt12 commented on src/components/layout/UnfoundData/styles.ts
> +  margin-top: 8px;
según entiendo eso era con el antiguo sistema de diseño ,ya ahora se le pase directamente

2024-09-04 21:28 UTC, diegoAndres01 requested changes

2024-09-04 21:28 UTC, diegoAndres01 commented on src/components/modals/CreditLimit/Stories/CreditLimit.stories.tsx
> +  buttonLabel: "Close", // Incluye el argumento buttonLabel
Remove comment

2024-09-04 21:28 UTC, diegoAndres01 commented on src/components/modals/CreditLimit/index.tsx
> +  buttonLabel?: string; // Asegúrate de incluir buttonLabel aquí
Remove comment

2024-09-04 21:28 UTC, diegoAndres01 commented on src/components/modals/CreditLimit/index.tsx
> +          {/* Botón de actualización */}
Remove comment

2024-09-04 22:15 UTC, diegoAndres01 approved these changes

2024-09-05 07:50 UTC, carin91 requested changes

2024-09-05 07:50 UTC, carin91 commented on src/pages/board/outlets/financialReporting/PromissoryNotes/index.tsx
> +        message: "Error al obtener los datos de Pagarés y Libranzas",
It is expected that the application returns the error reported by the backend. Therefore, i expect that the message uses the "error"

2024-09-05 07:50 UTC, carin91 commented on src/components/layout/UnfoundData/index.tsx
> +  onRetry?: () => void;
Relocate the route prop to line 11

2024-09-05 07:50 UTC, carin91 commented on src/pages/board/outlets/financialReporting/PromissoryNotes/index.tsx
> +              description="Hubo un error al intentar cargar los datos. Por favor, intente nuevamente."
It is expected that the application returns the error reported by the backend. Therefore, i expect that the message uses the "error"

2024-09-05 07:51 UTC, carin91 requested changes

2024-09-05 07:51 UTC, carin91 commented on src/pages/board/outlets/financialReporting/PromissoryNotes/index.tsx
Adjust the imports accordingly to the standard

2024-09-09 18:36 UTC, Angelbt12 commented on src/pages/board/outlets/financialReporting/PromissoryNotes/index.tsx
> +        message: "Error al obtener los datos de Pagarés y Libranzas",
ok

2024-09-09 18:36 UTC, Angelbt12 commented on src/pages/board/outlets/financialReporting/PromissoryNotes/index.tsx
> +              description="Hubo un error al intentar cargar los datos. Por favor, intente nuevamente."
ok

2024-09-09 18:36 UTC, Angelbt12 commented on src/pages/board/outlets/financialReporting/PromissoryNotes/index.tsx
ok

2024-09-20 09:43 UTC, carin91 approved these changes

2024-09-20 13:21 UTC, merged