cb186 Create the income modal
selsa-inube/crediboard pull request #156
Opened 2024-09-05 20:36 UTC by Brandonz07

create the component according to figma
![image](https://github.com/user-attachments/assets/6662823f-06f7-453c-8d03-7fe038866ead)

2024-09-12 13:14 UTC, diegoAndres01 requested changes

2024-09-12 13:14 UTC, diegoAndres01 commented on src/components/modals/IncomeModal/index.tsx
> +        margin="20px 0px 0px 0px"
Replace the margin property to padding and the measurements should be these 16px 0px 16px, with in the Figma

2024-09-12 13:14 UTC, diegoAndres01 commented on src/components/modals/IncomeModal/index.tsx
> +      >
Missing gap property for Stack component, with in Figma

2024-09-12 13:14 UTC, diegoAndres01 commented on src/components/modals/IncomeModal/index.tsx
> +            <Button children="Guardar" appearance="light"/>
In appearance it should be primary and you should add the disabled property

2024-09-12 13:14 UTC, diegoAndres01 commented on src/components/modals/IncomeModal/index.tsx
> +import { Select } from "@inubekit/select";
Sort imports

2024-09-12 13:14 UTC, diegoAndres01 commented on src/components/modals/IncomeModal/index.tsx
> +  return (
Since this component must be a Modal, it is necessary to add createPortal from react-dom, and the Blanket component from Inubekit (you can use src\components\modals\ListModal\index.tsx)

2024-09-12 21:57 UTC, diegoAndres01 requested changes

2024-09-12 21:57 UTC, diegoAndres01 commented on src/components/modals/IncomeModal/styles.ts
> +export const StyledContainer = styled.div`
The properties Gap, Radius, Padding, Height and Width need to be added; as is in Figma

2024-09-13 14:48 UTC, Brandonz07 commented on src/components/modals/IncomeModal/styles.ts
> +export const StyledContainer = styled.div`
some properties were added directly on the stack

2024-09-13 21:10 UTC, diegoAndres01 approved these changes

2024-09-25 01:06 UTC, carin91 approved these changes

2024-09-25 01:06 UTC, merged