At/cb 187 create the credit limit modal
selsa-inube/crediboard pull request #157
Opened 2024-09-09 14:27 UTC by Angelbt12

modal creation
![image](https://github.com/user-attachments/assets/24de6410-94ad-4b8e-bbe3-16b5cf395be5)
![image](https://github.com/user-attachments/assets/2b205048-4b1d-4691-bdf4-3202c2d39cfc)

2024-09-10 03:54 UTC, novadeveloper14 requested changes
Check the inubekit stack component so you can determine in which case it is better to create a styled component or in which case to use the Stack and pass the props to it. (same case with the grid but it has nothing to do with this task)

[Stack](https://github.com/selsa-inube/inubekit-stack/blob/main/src/Stack/index.tsx)

2024-09-10 03:54 UTC, novadeveloper14 commented on src/components/modals/CreditLimit/index.tsx
> +import { Blanket, Button, Stack, useMediaQuery } from "@inube/design-system";
use only inubekit components

2024-09-10 03:54 UTC, novadeveloper14 commented on src/components/modals/CreditLimit/index.tsx
> +  const formatCurrency = (amount: number) => {
We already have this function in the utils folder

2024-09-10 03:54 UTC, novadeveloper14 commented on src/components/modals/CreditLimit/index.tsx
> +  const maxUsableLimit = Math.min(
I think these calculations are data that is already passed from the backend. Let's try to pass the data directly to the component without performing calculations.

2024-09-10 03:54 UTC, novadeveloper14 commented on src/components/modals/CreditLimit/index.tsx
Let's remember to separate with a space: 

external imports (include @inubekit imports)
\\ 
internal imports with aliases
\\ 
internal imports without aliases

2024-09-10 03:54 UTC, novadeveloper14 commented on src/components/modals/CreditLimit/index.tsx
> +                • Endeudamiento máximo x FRC
For semantic reasons you should not do this (• ...). You have to create an html listing with ul and li tags.

2024-09-10 03:54 UTC, novadeveloper14 commented on src/components/modals/CreditLimit/stories/CreditLimit.stories.tsx
> +  parameters: {
This should be done in another file called props.ts inside stories and imported here to be referenced by other components such as src\components\cards\CreditProductCard\stories\CreditProductCard.stories.tsx. The English description of each prop is also missing.

2024-09-10 03:54 UTC, novadeveloper14 commented on src/components/modals/CreditLimit/stories/CreditLimit.stories.tsx
> +          <div id="portal"></div>
This is not necessary since in .storybook\preview-head.html we have the `<div id="portal"></div>` so all the storybook components that need to render things in this div would already work

2024-09-10 03:54 UTC, novadeveloper14 commented on src/components/modals/CreditLimit/styles.ts
> +  color: #28a745;
The color should be passed in the appearance of the text component. The margin can also be passed there. This styled component is not necessary.

2024-09-10 03:54 UTC, novadeveloper14 commented on src/components/modals/CreditLimit/styles.ts
> +  border-top: 2px solid #dfe1e6;
Always use colors from inube tokens 
![image](https://github.com/user-attachments/assets/152b3602-ee5a-4051-a3e9-4d6ec6a81b21)

2024-09-10 03:54 UTC, novadeveloper14 commented on src/components/modals/CreditLimit/styles.ts
> +  padding: 12px 0;
This can be done with a stack. This styled component is not necessary.

2024-09-10 03:54 UTC, novadeveloper14 commented on src/components/modals/CreditLimit/styles.ts
> +  align-items: center;
This can be done with a stack. This styled component is not necessary.

2024-09-10 03:54 UTC, novadeveloper14 commented on src/components/modals/CreditLimit/styles.ts
> +  margin-top: 10px;
This can be done with a stack. This styled component is not necessary.

2024-09-10 03:54 UTC, novadeveloper14 commented on src/components/modals/CreditLimit/styles.ts
> +  justify-content: end;
This can be done with a stack. This styled component is not necessary.

2024-09-10 03:54 UTC, novadeveloper14 commented on src/components/modals/CreditLimit/styles.ts
> +  flex-direction: column;
This can be done with a stack. This styled component is not necessary.

2024-09-10 03:54 UTC, novadeveloper14 commented on src/components/modals/CreditLimit/styles.ts
> +  margin: 0px;
This can be done with a stack. This styled component is not necessary.

2024-09-10 12:21 UTC, Angelbt12 commented on src/components/modals/CreditLimit/index.tsx
> +import { Blanket, Button, Stack, useMediaQuery } from "@inube/design-system";
ok

2024-09-10 12:37 UTC, Angelbt12 commented on src/components/modals/CreditLimit/index.tsx
ok

2024-09-10 13:02 UTC, Angelbt12 commented on src/components/modals/CreditLimit/stories/CreditLimit.stories.tsx
> +          <div id="portal"></div>
ok

2024-09-10 13:28 UTC, Angelbt12 commented on src/components/modals/CreditLimit/index.tsx
> +                • Endeudamiento máximo x FRC
ok

2024-09-10 13:28 UTC, Angelbt12 commented on src/components/modals/CreditLimit/index.tsx
ok

2024-09-10 13:28 UTC, Angelbt12 commented on src/components/modals/CreditLimit/index.tsx
> +import { Blanket, Button, Stack, useMediaQuery } from "@inube/design-system";
ok

2024-09-10 13:29 UTC, Angelbt12 commented on src/components/modals/CreditLimit/index.tsx
> +  const formatCurrency = (amount: number) => {
ok

2024-09-10 13:29 UTC, Angelbt12 commented on src/components/modals/CreditLimit/index.tsx
> +  const maxUsableLimit = Math.min(
ok

2024-09-10 13:29 UTC, Angelbt12 commented on src/components/modals/CreditLimit/styles.ts
> +  color: #28a745;
ok

2024-09-10 13:30 UTC, Angelbt12 commented on src/components/modals/CreditLimit/styles.ts
> +  border-top: 2px solid #dfe1e6;
ok

2024-09-10 13:33 UTC, Angelbt12 commented on src/components/modals/CreditLimit/styles.ts
> +  padding: 12px 0;
ok

2024-09-10 13:49 UTC, Angelbt12 commented on src/components/modals/CreditLimit/styles.ts
> +  margin-top: 10px;
ok

2024-09-10 13:56 UTC, Angelbt12 commented on src/components/modals/CreditLimit/styles.ts
> +  justify-content: end;
ok

2024-09-10 14:00 UTC, Angelbt12 commented on src/components/modals/CreditLimit/styles.ts
> +  flex-direction: column;
ok

2024-09-10 14:04 UTC, Angelbt12 commented on src/components/modals/CreditLimit/styles.ts
> +  margin: 0px;
ok

2024-09-11 08:25 UTC, novadeveloper14 requested changes

2024-09-11 08:25 UTC, novadeveloper14 commented on src/components/modals/CreditLimit/stories/props.ts
> +export const props: ArgTypes = {
You need to pass the type to avoid typescript typing errors



![image](https://github.com/user-attachments/assets/15c5a4ee-4c85-46b4-a2ee-846f30dbc4c3)

2024-09-11 08:27 UTC, novadeveloper14 approved these changes

2024-09-11 08:28 UTC, novadeveloper14 commented on src/components/modals/CreditLimit/stories/props.ts
> +export const props: ArgTypes = {
Go to Camilo's review directly when the comment is resolved

2024-09-11 12:25 UTC, Angelbt12 commented on src/components/modals/CreditLimit/stories/props.ts
> +export const props: ArgTypes = {
ok

2024-09-18 11:25 UTC, carin91 approved these changes

2024-09-18 11:25 UTC, carin91 commented on src/components/modals/CreditLimit/index.tsx
> +              <Text>Cerrar</Text>
Relocate this into a config file

2024-09-18 11:25 UTC, carin91 commented on src/components/modals/CreditLimit/index.tsx
> +                  Cupo máximo según capacidad de pago
Relocate this into a config file

2024-09-18 11:25 UTC, carin91 commented on src/components/modals/CreditLimit/index.tsx
> +                  Cupo máximo por reciprocidad
Relocate this into a config file

2024-09-18 11:25 UTC, carin91 commented on src/components/modals/CreditLimit/index.tsx
> +                  Endeudamiento máximo x FRC
Relocate this into a config file

2024-09-18 11:25 UTC, carin91 commented on src/components/modals/CreditLimit/index.tsx
> +                  Cupo individual asignado
Relocate this into a config file

2024-09-18 11:25 UTC, carin91 commented on src/components/modals/CreditLimit/index.tsx
> +              El menor de los anteriores es su cupo
Relocate this into a config file

2024-09-18 11:25 UTC, carin91 commented on src/components/modals/CreditLimit/index.tsx
> +            <Text weight="bold">Cupo máximo utilizable</Text>
Relocate this into a config file

2024-09-18 11:25 UTC, carin91 commented on src/components/modals/CreditLimit/index.tsx
> +            <Text size="large" appearance="gray" weight="bold">(-) Cartera vigente</Text>
Relocate this into a config file

2024-09-18 11:25 UTC, carin91 commented on src/components/modals/CreditLimit/index.tsx
> +            <Text weight="bold">Cupo disponible sin garantía</Text>
Relocate this into a config file

2024-09-18 13:06 UTC, Angelbt12 commented on src/components/modals/CreditLimit/index.tsx
> +              <Text>Cerrar</Text>
ok

2024-09-18 13:06 UTC, Angelbt12 commented on src/components/modals/CreditLimit/index.tsx
> +                  Cupo máximo según capacidad de pago
ok

2024-09-18 13:06 UTC, Angelbt12 commented on src/components/modals/CreditLimit/index.tsx
> +                  Cupo máximo por reciprocidad
ok

2024-09-18 13:06 UTC, Angelbt12 commented on src/components/modals/CreditLimit/index.tsx
> +                  Endeudamiento máximo x FRC
ok

2024-09-18 13:06 UTC, Angelbt12 commented on src/components/modals/CreditLimit/index.tsx
> +                  Cupo individual asignado
ok

2024-09-18 13:06 UTC, Angelbt12 commented on src/components/modals/CreditLimit/index.tsx
> +            <Text weight="bold">Cupo disponible sin garantía</Text>
ok

2024-09-19 12:59 UTC, merged