Include props of layout L004/L005
selsa-inube/crediboard pull request #16
Opened 2024-04-20 06:04 UTC by novadeveloper14

The layout L004 receive an array with the information which will be passed to SummaryCard.

this component include the rendering of C001 and maps this prop array to render the cards information.

This task includes the creation of a component which renders L004 or L005 and manage the passing of this array.

Include operation of CU003.

![image](https://github.com/selsa-inube/crediboard/assets/87447257/b9a924a5-9057-4546-8771-fe280c4a0779)

2024-04-22 15:00 UTC, Andresbl123 commented on src/utils/formatData/date.ts
> +  const month = monthNames[date.getMonth()];
aquí nos podríamos ahorrar el array de `monthNames`, utilizando el método `toLocaleString` de `Date` algo así: `const month = date.toLocaleString("es-CO", {month: "long" })` esto odebería dar el mismo resultad

2024-04-22 15:21 UTC, Andresbl123 commented on src/utils/formatData/text.ts
> +  return text
esto se podría mejorar y simplificar mucho usando el método `replace` , pasándole como primer argumento una expresión regular, para capturar la palabra y en el callback la capitalizamos usando  el método `toUpperCaseI`, algo como: `/\b\w/g, (word) => word.toUpperCaseI()`

2024-04-23 04:27 UTC, novadeveloper14 commented on src/components/cards/SummaryCard/index.tsx
> +        <Text type="label">{truncateTextToMaxLength(toDo, 60)}</Text>
The ellipsis of the component does not allow line breaks, which can be seen in the designs if it is allowed. that's why this utility was used.

with ellipsis:

![image](https://github.com/selsa-inube/crediboard/assets/87447257/97425649-061b-495c-8857-7c65fe60ad9a)

desings:

![image](https://github.com/selsa-inube/crediboard/assets/87447257/6cbec587-453e-4fdb-aa48-79cac8072d78)

2024-04-23 14:34 UTC, Andresbl123 approved these changes

2024-04-24 15:29 UTC, carin91 commented on src/components/cards/SummaryCard/index.tsx
>      props;
assign a default false value to isPinned and hasMessage to avoid coersion.

2024-04-24 15:42 UTC, carin91 commented on src/components/layout/BoardSection/stories/BoardSection.stories.tsx
> +  sectionInformation: mockRequests,
You must consume the mocked service, as an example look at this:


  const [dataAddPositionLinixForm, setDataAddPositionLinixForm] =
    useState<IFormAddPosition>({
      generalInformation: {
        isValid: false,
        values: initalValuesPositions.generalInformation,
      },
      roles: {
        isValid: false,
        values: [],
      },
    });

  useEffect(() => {
    getAll("linix-roles")
      .then((data) => {
        if (data !== null) {
          setDataAddPositionLinixForm((prevFormData) => ({
            ...prevFormData,
            roles: {
              isValid: true,
              values: dataToAssignmentFormEntry({
                dataOptions: data as Record<string, unknown>[],
                idLabel: "k_Rol",
                valueLabel: "n_Rol",
                isActiveLabel: "asignado",
              }),
            },
          }));
        }
      })
      .catch((error) => {
        console.error("Error fetching roles:", error.message);
      });
  }, []);

2024-04-24 16:04 UTC, carin91 requested changes

2024-04-24 16:04 UTC, carin91 commented on src/utils/formatData/text.ts
> +  return text.toLowerCase().replace(/\b\w/g, (word) => word.toUpperCase());
Adjust this function considering the "tilde" character in spanish.

I would try this:
function capitalizeFirstLetter(text: string) {
  return text
    .toLowerCase()
    .replace(/(^|[\s\u200B])\w/g, (character) => character.toUpperCase());
}

Add to it, avoid the use of this util in the "Destination" and "ToDo" field, considering that it is a grammatical mistake in spanish.

2024-04-25 08:35 UTC, merged