At/cb 190 create the credit limit modal for income
selsa-inube/crediboard pull request #160
Opened 2024-09-11 21:40 UTC by Angelbt12

Create the credit limit modal for income
![image](https://github.com/user-attachments/assets/5e0049ed-58ce-4361-83a1-5c8213fd4450)
The taskk includes:

(1) desktop version

(2) mobile version

(3) loading version

(4) error version

2024-09-13 07:55 UTC, novadeveloper14 approved these changes

2024-09-18 12:12 UTC, carin91 requested changes

2024-09-18 12:12 UTC, carin91 commented on src/components/modals/IncomeModal/index.tsx
> +              Error cargando datos
Relocate this into a config file

2024-09-18 12:12 UTC, carin91 commented on src/components/modals/IncomeModal/index.tsx
> +              No se pudieron cargar los datos. Por favor, intente nuevamente más
Relocate all of the data rendered into a config file

2024-09-18 12:12 UTC, carin91 commented on src/components/modals/IncomeModal/index.tsx
> +    <Blanket>
Refactor the component dividing it between index and interface

2024-09-18 13:06 UTC, Angelbt12 commented on src/components/modals/IncomeModal/index.tsx
> +              Error cargando datos
ok

2024-09-18 13:06 UTC, Angelbt12 commented on src/components/modals/IncomeModal/index.tsx
> +              No se pudieron cargar los datos. Por favor, intente nuevamente más
ok

2024-09-18 20:13 UTC, Angelbt12 commented on src/components/modals/IncomeModal/index.tsx
> +    <Blanket>
It's not very clear to me

2024-09-27 15:39 UTC, carin91 approved these changes

2024-09-27 15:39 UTC, merged