cb189 Create the reported credits modal
selsa-inube/crediboard pull request #161
Opened 2024-09-11 23:54 UTC by Brandonz07

create the component according to figma

2024-09-12 22:35 UTC, diegoAndres01 requested changes

2024-09-12 22:35 UTC, diegoAndres01 commented on src/components/modals/ReportCreditsModal/styles.ts
> +export const StyledContainer = styled.div`
The properties Gap, Radius, Height and Width need to be added; as is in Figma

2024-09-12 22:35 UTC, diegoAndres01 commented on src/components/modals/ReportCreditsModal/index.tsx
> +                  <Th key={index} action={header.action} align="center">
The Align property must be left

2024-09-12 22:35 UTC, diegoAndres01 commented on src/components/modals/ReportCreditsModal/index.tsx
> +                      <Td
missing align property with value left:
`align={header.action ? "center" : "left"}`

2024-09-12 22:35 UTC, diegoAndres01 commented on src/components/modals/ReportCreditsModal/Detail/index.tsx
> +          icon={<MdLinearScale />}
Change icon by:
`icon={<MdOutlineMoreVert />}`

2024-09-12 22:35 UTC, diegoAndres01 commented on src/components/modals/ReportCreditsModal/index.tsx
> +            <Textfield
The Value property of the total quota is missing

2024-09-12 22:35 UTC, diegoAndres01 commented on src/components/modals/ReportCreditsModal/index.tsx
> +            <Textfield
The Value property of the balance total is missing

2024-09-13 22:41 UTC, diegoAndres01 requested changes

2024-09-17 23:09 UTC, diegoAndres01 requested changes

2024-09-17 23:09 UTC, diegoAndres01 commented on src/components/modals/ReportCreditsModal/index.tsx
> +                      <Th key={index}>
This error is being generated in the browser console:

![image](https://github.com/user-attachments/assets/dcda9518-2c5f-42c4-8b3c-cbffb62d1252)

This is because a div is being added inside a p tag.

![image](https://github.com/user-attachments/assets/15f2bfaa-5fd9-4b3a-b0eb-376ae2ec5dfb)

To solve this, change the label to Td and add the type property with the custom value. 

` <Td key={index} type="custom"> <SkeletonIcon /> </Td> `

2024-09-17 23:09 UTC, diegoAndres01 commented on src/components/modals/ReportCreditsModal/index.tsx
> +                        <Td key={index}>
Add the Type property with the value custom

2024-09-17 23:09 UTC, diegoAndres01 commented on src/components/modals/ReportCreditsModal/index.tsx
> +                      <Td colSpan={visibleHeaders.length} align="center">
Add the Type property with the value custom

2024-09-19 21:04 UTC, diegoAndres01 approved these changes

2024-09-25 01:22 UTC, carin91 requested changes

2024-09-25 01:22 UTC, carin91 commented on src/components/modals/ReportCreditsModal/interface.tsx
> +import { useState } from "react";
avoid the words in spanish

2024-09-25 01:22 UTC, carin91 commented on src/components/modals/ReportCreditsModal/interface.tsx
> +interface RowData {
Refactor the component considering the separation between index and interface.

2024-09-27 15:37 UTC, carin91 approved these changes

2024-09-27 15:37 UTC, merged