At/cb 191 minors 3
selsa-inube/crediboard pull request #163
Opened 2024-09-13 21:29 UTC by Angelbt12

Header: 
Alineación y espaciado: 
Padding: El logo del cliente y el icono que permite cambiar de cliente, deberían estar un poco más juntos entre sí, espaciado S-100.
btnVolver: 
Tamaño: 
Pierde un poco de consistencia al no estar alineado con el resto de componentes en pantalla, se propone un botón de tipo outlined.
Alineación y espaciado: 
Alineado con el cuerpo del aplicativo.
Espaciado entre elementos de ese contenedor: S-200
Iconografía: 
Un icono más consistente y agradable, flecha sencilla (Chevron left).
Header de prospecto
Tamaño:
btn “Ver perfil crediticio” de la misma altura de los de llamada y videollamada.
Icono de flecha que permite desplegar o extender, un poco más pequeño, 28 px.
Flecha para desplegar tarjeta más pequeña.
Alineación y espaciado: 
Acciones (botones) a la derecha.
Nombre del titular “centrado”.
Flecha para desplegar tarjeta aparte para evitar presión de videollamada accidental.
Iconografía: Acciones puntuales solo con icono, no botón outlined.

2024-09-16 21:10 UTC, Brandonz07 requested changes
To fix the padding in the header, I propose the following

in the file
components/layout/AppPage/styles.ts

in StyledLogo add a ```padding-left: 20px;```

and create another StyledHeader component that wraps the header in
appPage/index.tsx

```const StyledHeader = styled.div`
div:nth-child(2){
padding-right: 20px;
}```

2024-09-16 21:10 UTC, Brandonz07 commented on package-lock.json
try not to modify the lock, try this code to bring lock.json from main

git checkout main -- package-lock.json

2024-09-16 22:54 UTC, Brandonz07 approved these changes

2024-09-18 12:14 UTC, carin91 approved these changes

2024-09-18 12:20 UTC, carin91 requested changes

2024-09-18 12:20 UTC, carin91 commented on src/components/layout/AppPage/styles.ts
> +const StyledHeader = styled.div`
Avoid modifying the design-system by the container. Could you refactor this to use the design-system component? if not, verify a new proposal with Sergio.

2024-09-18 12:20 UTC, carin91 commented on src/components/layout/ContainerSections/StockTray/index.tsx
> +          Volver
Relocate all of the data rendered into a config file

2024-09-18 14:41 UTC, Angelbt12 commented on src/components/layout/ContainerSections/StockTray/index.tsx
> +          Volver
ok

2024-09-20 09:51 UTC, carin91 approved these changes

2024-09-20 09:51 UTC, merged