cb192 minors4
selsa-inube/crediboard pull request #164
Opened 2024-09-16 02:45 UTC by Brandonz07

![image](https://github.com/user-attachments/assets/f06489c5-7d6b-474e-a4d2-5ecf8027cf72)

2024-09-16 12:19 UTC, Angelbt12 approved these changes
meets the requirements

2024-09-19 17:15 UTC, carin91 requested changes

2024-09-19 17:15 UTC, carin91 commented on src/pages/board/outlets/financialReporting/ToDo/index.tsx
> +              justifyContent="end"
Relocate to send button to its original position:
![image](https://github.com/user-attachments/assets/df58d6ac-b409-433f-8f43-c7e7f2968911)

2024-09-19 17:15 UTC, carin91 commented on src/pages/board/outlets/financialReporting/ToDo/index.tsx
>                  {button?.label || "Enviar"}
Every spanish text must be located in a config file

2024-09-19 17:15 UTC, carin91 commented on src/pages/board/outlets/financialReporting/ToDo/index.tsx
>              {icon && !isMobile && (
Aligned the icon with the analyst and commercial text fields. Its current location seems invalid.
![image](https://github.com/user-attachments/assets/d937a88e-b423-402f-98d7-2e189acd6f7a)

2024-09-19 17:15 UTC, carin91 commented on src/pages/board/outlets/financialReporting/ToDo/index.tsx
>                  loading={button?.loading || false}
![image](https://github.com/user-attachments/assets/dcb7c972-8e85-4cb7-aac0-2d63287ead48)
aligned the send button with the text field

2024-09-25 01:43 UTC, carin91 approved these changes
![image](https://github.com/user-attachments/assets/eef4065b-10b2-45c3-9ce9-ddb628276082)
Adjust the error

2024-09-26 17:30 UTC, merged