Create layout l009 `<PromissoryMotes />`
selsa-inube/crediboard pull request #17
Opened 2024-04-23 21:58 UTC by Andresbl123

The section of promissory notes and promissory notes is created, where a table is rendered with the data for this section, to show the data a configuration file is created that can be modified as the services are implemented for the consumption of the API with the information.

2024-04-26 07:56 UTC, novadeveloper14 approved these changes

2024-04-30 12:22 UTC, carin91 requested changes
Adjust the width of the promissory Notes
![image](https://github.com/selsa-inube/crediboard/assets/123512032/0d1d1301-7678-4fb9-8117-618a85d824aa)

2024-04-30 12:22 UTC, carin91 commented on src/pages/board/outlets/PromissoryNotes/index.tsx
> +import { Fieldset } from "@src/components/data/Fieldset";
@components

2024-04-30 12:22 UTC, carin91 commented on src/pages/board/outlets/PromissoryNotes/index.tsx
> +import { TableBoard } from "@src/components/data/TableBoard";
@components

2024-05-02 08:41 UTC, carin91 approved these changes

2024-05-02 08:41 UTC, merged