footer implementation
selsa-inube/crediboard pull request #178
Opened 2024-09-20 21:05 UTC by Angelbt12

the footer must be implemented in the credit profile
![image](https://github.com/user-attachments/assets/5a1aa3c5-1753-4b31-8178-14b332e55c72)

2024-09-24 15:05 UTC, novadeveloper14 requested changes

2024-09-24 15:05 UTC, novadeveloper14 commented on src/components/layout/AppPage/index.tsx
> +            <Stack
The recommendation was not to use a stack but a styled component where the footer type is passed to maintain the basic semantics of a page.

![image](https://github.com/user-attachments/assets/2b4c651a-9d66-429a-bfa8-a8328e87f681)

2024-09-24 15:05 UTC, novadeveloper14 commented on src/components/layout/AppPage/index.tsx
> +              padding=" 16px 24px 16px 24px"
You can refactor it like this: padding=" 16px 24px"

2024-09-24 15:05 UTC, novadeveloper14 commented on src/components/layout/AppPage/index.tsx
> +                type="body"
text already has body type by default, there is no need to pass it

2024-09-24 15:46 UTC, Angelbt12 commented on src/components/layout/AppPage/index.tsx
> +              gap="10px"
ok

2024-09-24 15:48 UTC, Angelbt12 commented on src/components/layout/AppPage/index.tsx
> +            <Stack
ok

2024-09-24 15:48 UTC, Angelbt12 commented on src/components/layout/AppPage/index.tsx
> +              padding=" 16px 24px 16px 24px"
ok

2024-09-25 13:19 UTC, novadeveloper14 requested changes

2024-09-25 13:19 UTC, novadeveloper14 commented on src/components/layout/AppPage/index.tsx
> +            <Footer>
Every styled component should be called Styled so as not to confuse it with normal components. It would be StyledFooter

2024-09-25 15:23 UTC, Angelbt12 commented on src/components/layout/AppPage/index.tsx
> +            <Footer>
ok

2024-09-27 06:02 UTC, novadeveloper14 approved these changes

2024-09-27 15:40 UTC, carin91 approved these changes

2024-09-27 15:40 UTC, merged