Ab/cb30/create layout l008 requirements
selsa-inube/crediboard pull request #18
Opened 2024-04-25 19:02 UTC by Andresbl123

Implement the `Requirements` component to improve the way requirements are visualised. Key changes include:

this section will show the requirements mock to implement the layout, which will be implemented. 

Updated the `Fieldset` component to include a ‘Requirements’ heading.

Mapped through the data passed to `Requirements` to generate multiple `TableBoard` components. Each `TableBoard` receives a unique set of `titles`, `entries` and `actions`.

![image](https://github.com/selsa-inube/crediboard/assets/74839801/00274ad3-9569-48a8-827d-63d931889e89)
![image](https://github.com/selsa-inube/crediboard/assets/74839801/adb97200-2533-4d58-ba43-2d9ba72b54f3)

2024-04-26 08:05 UTC, novadeveloper14 requested changes
The component must have the "Add requirements" button. according to what is seen in the requirements of the task in Jira

![image](https://github.com/selsa-inube/crediboard/assets/87447257/c9669dc7-6082-41c4-84c8-9dddae34b9c3)

2024-04-26 08:05 UTC, novadeveloper14 commented on src/pages/board/outlets/boardlayout/Requirements/index.tsx
> +      <Fieldset title="Requerimientos">
should say "Requisitos":

![image](https://github.com/selsa-inube/crediboard/assets/87447257/41033c10-f45a-48b2-91de-0445400ff7d3)

2024-04-26 14:34 UTC, carin91 requested changes

2024-04-26 16:59 UTC, Andresbl123 commented on src/pages/board/outlets/boardlayout/Requirements/index.tsx
> +      <Fieldset title="Requerimientos">
resuelto

2024-04-27 00:28 UTC, Andresbl123 commented on src/pages/board/outlets/boardlayout/Requirements/config.tsx
> +        <div style={{ display: "flex", justifyContent: "center" }}>
resuelto

2024-04-27 00:28 UTC, Andresbl123 commented on src/pages/board/outlets/boardlayout/Requirements/config.tsx
> +        <div style={{ display: "flex", justifyContent: "center" }}>
resuelto

2024-04-27 00:28 UTC, Andresbl123 commented on src/App.tsx
> +      <Route
resuelto

2024-04-27 00:28 UTC, Andresbl123 commented on src/pages/board/outlets/boardlayout/Requirements/index.tsx
> +    <Stack>
resuelto

2024-04-28 08:06 UTC, novadeveloper14 approved these changes

2024-04-28 11:00 UTC, carin91 commented on src/pages/board/outlets/boardlayout/Requirements/index.tsx
> +    <Stack>
The layout rendered seems invalid.

Validate the gap of the (+) and (check) buttons, as the location of the tags.

![image](https://github.com/selsa-inube/crediboard/assets/123512032/1b5405a1-79d1-4276-86c4-31d9d6174ff5)

2024-04-28 11:03 UTC, carin91 commented on src/App.tsx
> +      <Route
This task is pending

2024-04-29 14:11 UTC, Andresbl123 commented on src/pages/board/outlets/boardlayout/Requirements/index.tsx
> +    <Stack>
resuelto

2024-04-29 16:18 UTC, Andresbl123 commented on src/App.tsx
> +      <Route
resuelto

2024-04-30 11:52 UTC, carin91 approved these changes

2024-04-30 11:52 UTC, merged