At/cb 218 implement every modal on the prospect
selsa-inube/crediboard pull request #182
Opened 2024-09-30 12:33 UTC by Angelbt12

Implement every modal on the prospect

2024-10-07 20:53 UTC, diegoAndres01 requested changes

2024-10-07 20:53 UTC, diegoAndres01 commented on src/pages/board/outlets/financialReporting/CommercialManagement/index.tsx
>  import { incomeOptions } from "./config/config";
leave exports of the same file on a single line

![image](https://github.com/user-attachments/assets/b3bd7352-4562-4e82-8419-2fcb8875aa68)

2024-10-08 19:19 UTC, diegoAndres01 approved these changes

2024-10-11 11:44 UTC, carin91 approved these changes

2024-10-11 11:44 UTC, merged