At/cb 219 adjust the income modal
selsa-inube/crediboard pull request #183
Opened 2024-09-30 16:34 UTC by Angelbt12

Adjust the income modal accordingly to the mockups

2024-10-07 20:37 UTC, diegoAndres01 requested changes

2024-10-07 20:37 UTC, diegoAndres01 commented on src/components/modals/IncomeModal/index.tsx
>    return createPortal(
relocate to /src/pages/prospect/components

2024-10-07 20:37 UTC, diegoAndres01 commented on src/components/modals/IncomeModal/index.tsx
>              <Stack
missing add width property with value `width={!isMobile ? "auto" : "100%"}` 

Because in the mobile version it doesn't look like in the mockups

![image](https://github.com/user-attachments/assets/6680681f-6f40-439c-88e8-6820f539f1d1)

Figma

![image](https://github.com/user-attachments/assets/118030ea-0333-4866-96a0-12b969db2058)

2024-10-08 19:24 UTC, diegoAndres01 approved these changes

2024-10-11 11:45 UTC, carin91 approved these changes

2024-10-11 11:45 UTC, merged