Adjust SelectCheck (filter) required prop
selsa-inube/crediboard pull request #185
Opened 2024-10-01 14:20 UTC by Angelbt12

[Adjust SelectCheck (filter) required prop · Issue #167 · selsa-inube/crediboard](https://github.com/selsa-inube/crediboard/issues/167)

2024-10-01 16:56 UTC, novadeveloper14 approved these changes

2024-10-04 15:17 UTC, carin91 requested changes

2024-10-04 15:17 UTC, carin91 commented on src/components/inputs/SelectCheck/interface.tsx
>                  (Requerido)
Relocate every spanish word into a config file

2024-10-07 12:55 UTC, Angelbt12 commented on src/components/inputs/SelectCheck/interface.tsx
>                  (Requerido)
ok

2024-10-11 11:38 UTC, merged