cb-230 integration for `<Approvals />`
selsa-inube/crediboard pull request #189
Opened 2024-10-05 03:40 UTC by Andresbl123

Integrate the service related to “approvals”

branch: feature-CDB-44

Endpoint: http://localhost:8077/icorebanking-vi-crediboard-query-process-service/api//credit-request/aprovals/{creditRequestId}

AC:SearchAllAprovalsById

x-business-unit: test

https://gitlab.inube.com.co/icorebanking-vi/icorebanking-vi-crediboard-query-process-service/-/tree/feature-CDB-44?ref_type=heads

Documentation:

https://gitlab.inube.com.co/icorebanking-vi/icorebanking-vi-crediboard-query-process-service/-/blob/feature-CDB-44/api/rest/swagger.json?ref_type=heads

![image](https://github.com/user-attachments/assets/7c0a87e2-ff08-4c0f-bead-9bf031e73ba8)

![image](https://github.com/user-attachments/assets/f665e487-fc9d-4b77-860f-db81450fcd85)

2024-10-07 16:24 UTC, diegoAndres01 requested changes

2024-10-07 16:24 UTC, diegoAndres01 commented on src/pages/board/outlets/financialReporting/Approvals/config.tsx
> +    "http://192.168.31.62:8077/icorebanking-vi-crediboard-query-process-service/api/credit-requests/aprovals/",
Create it in an environment variable

2024-10-07 16:24 UTC, diegoAndres01 commented on src/utils/hooks/useFetch.ts
> +export function useFetch<T>(apiUrl: string, retryFlag: boolean) {
Create it in the service folder

2024-10-09 20:48 UTC, diegoAndres01 approved these changes

2024-12-19 20:33 UTC, carin91 approved these changes

2024-12-19 20:33 UTC, carin91 commented on src/config/pages/board/oulet/financialReporting/configApprovals.tsx
>    MdWarningAmber,
Rename the folder "oulet" to "outlet"

2024-12-19 20:33 UTC, carin91 commented on src/config/pages/board/oulet/financialReporting/configApprovals.tsx
> +  { icon: <MdCheck />, text: "Aprobado" },
It is necessary to assign a color and an icon to each of the five possible values for this field. Sergio will add the additional values to the mockups in Figma

2024-12-26 15:39 UTC, carin91 approved these changes

2024-12-26 15:39 UTC, merged