Create the visual version of layout L001 - Include the visual version of Layout L003
selsa-inube/crediboard pull request #19
Opened 2024-04-26 07:45 UTC by novadeveloper14

This task includes the requirements of tasks CB4 - CB6 and a part of CB7.

In this task the board was rendered on the home screen of the application. where some related components had to be modified to achieve the best user experience when using the application board.

This task included the operation of the state that changes the orientation of the table, so when you click on the icons that will work, I did this to facilitate the review of the board in its horizontal version and in this way complete the task CB6.

For task CB7 I plan to adjust the other functionalities of the application as they will be:

- the search engine where the SummaryCards will be filtered
- the Switch where the option will be activated to only show the SummaryCards that are pinned.
-filtering by options (depending on the availability of the CU004 component)

With this all the functionalities would be working.

2024-04-26 16:18 UTC, Andresbl123 commented on src/pages/board/outlets/boardlayout/styles.ts
> +  padding: ${inube.spacing.s400} ${inube.spacing.s600} ${inube.spacing.s200};
aquí podríamos separar cada `padding` que se necesite para poder implementar el `theme` de una forma legible

2024-04-26 16:18 UTC, Andresbl123 commented on src/pages/board/outlets/boardlayout/index.tsx
> +  }, []);
Me parece que aquí en el array de dependencias debería ir `boardData`, con esto se sincroniza con la data, el efecto se ejecutara cuando cambie la data, cosa que pienso que de alguna forma es mejor y no como esta ahora que se ejecutara cada vez que se renderice el componente.

2024-04-26 17:03 UTC, Andresbl123 approved these changes

2024-04-27 10:04 UTC, carin91 requested changes

2024-04-27 10:04 UTC, carin91 commented on src/pages/board/outlets/boardlayout/interface.tsx
> +              ></Switch>
This switch will never have children. Can you use the self-closing brackets?

2024-04-27 10:04 UTC, carin91 commented on src/pages/board/outlets/boardlayout/styles.ts
> +  gap: ${inube.spacing.s500};
refactor to validate the theme

2024-04-28 05:08 UTC, novadeveloper14 commented on src/App.tsx
> +      <Route path="*" element={<FirstPage />} errorElement={<ErrorPage />} />
The objective of this change is to avoid the following warning in the console:

![image](https://github.com/selsa-inube/crediboard/assets/87447257/73a68d82-3f02-44aa-8edf-278ff86957e3)

2024-04-28 07:20 UTC, novadeveloper14 commented on src/pages/board/outlets/boardlayout/interface.tsx
> +import { MdOutlinePushPin, MdSearch } from "react-icons/md";
The size of each BoardSection in figma is not 278px is just different in each column, so the min-width that the component had was eliminated.

![image](https://github.com/selsa-inube/crediboard/assets/87447257/217e00f0-b049-4db9-9412-cd044c551c0f)
![image](https://github.com/selsa-inube/crediboard/assets/87447257/6aeef7d2-a81e-427b-ae65-8eaf119e3aaa)

In any case, some parameters were modified to avoid the scroll-x that was occurring.

![image](https://github.com/selsa-inube/crediboard/assets/87447257/3f6387f2-ef43-461b-8248-451cc8bbd000)

2024-04-28 10:53 UTC, carin91 approved these changes

2024-04-28 10:53 UTC, merged