At/cb233/implement the add series modal
selsa-inube/crediboard pull request #191
Opened 2024-10-07 12:55 UTC by Angelbt12

![image](https://github.com/user-attachments/assets/bc4be0e7-d503-4ac5-bb7f-bb2a2c7c0b3e)

2024-10-08 20:30 UTC, diegoAndres01 requested changes

2024-10-08 20:30 UTC, diegoAndres01 commented on src/components/modals/AddSeriesModal/index.tsx
> +export interface Option {
Relocate interface in type.ts file

2024-10-08 20:30 UTC, diegoAndres01 commented on src/components/modals/AddSeriesModal/index.tsx
> +    paymentMethod: "",
Create interface

2024-10-08 20:30 UTC, diegoAndres01 commented on src/components/modals/AddSeriesModal/index.tsx
> +    const numericValue = value.replace(/[^0-9]/g, "");
For validations you can implement Formik

2024-10-08 20:30 UTC, diegoAndres01 commented on src/components/modals/AddSeriesModal/index.tsx
> +            <Stack alignItems="center" gap={inube.spacing.s100}>
Design-system space should not be implemented

2024-10-08 20:30 UTC, diegoAndres01 commented on src/components/modals/AddSeriesModal/index.tsx
> +              <Text>Cerrar</Text>
Texts should be left in config

2024-10-08 20:30 UTC, diegoAndres01 commented on src/components/modals/AddSeriesModal/index.tsx
> +            type="text"
The type must be number

2024-10-08 20:30 UTC, diegoAndres01 commented on src/components/modals/AddSeriesModal/index.tsx
> +        <Stack justifyContent="flex-end" margin="s200 s0" gap="10px">
Invalid margin value

2024-10-08 20:30 UTC, diegoAndres01 commented on src/components/modals/AddSeriesModal/stories/PromissoryNotesModal.stories.tsx
> +import { Button } from "@inube/design-system";
Do not use inube/design-system

2024-10-08 20:30 UTC, diegoAndres01 commented on src/components/modals/AddSeriesModal/stories/PromissoryNotesModal.stories.tsx
> +};
Missing add parameters property for general component documentation

2024-10-08 20:30 UTC, diegoAndres01 commented on src/components/modals/AddSeriesModal/styles.ts
> +import { inube } from "@inube/design-system";
Do not use inube/design-system

2024-10-09 12:37 UTC, Angelbt12 commented on src/components/modals/AddSeriesModal/index.tsx
> +export interface Option {
ok

2024-10-09 13:51 UTC, Angelbt12 commented on src/components/modals/AddSeriesModal/index.tsx
> +              <Text>Cerrar</Text>
ok

2024-10-09 13:51 UTC, Angelbt12 commented on src/components/modals/AddSeriesModal/index.tsx
> +            type="text"
ok

2024-10-09 15:20 UTC, Angelbt12 commented on src/components/data/TableExtraordinaryInstallment/Detail/index.tsx
>  import { Stack } from "@inubekit/stack";
ok

2024-10-09 15:20 UTC, Angelbt12 commented on src/components/modals/AddSeriesModal/index.tsx
> +        <Stack justifyContent="flex-end" margin="s200 s0" gap="10px">
ok

2024-10-09 15:22 UTC, Angelbt12 commented on src/components/modals/AddSeriesModal/stories/PromissoryNotesModal.stories.tsx
> +import { Button } from "@inube/design-system";
ok

2024-10-09 15:25 UTC, Angelbt12 commented on src/components/modals/AddSeriesModal/styles.ts
> +import { inube } from "@inube/design-system";
ok

2024-10-09 15:29 UTC, Angelbt12 commented on src/components/data/TableExtraordinaryInstallment/Detail/index.tsx
> +        <Icon
ok

2024-10-09 16:19 UTC, Angelbt12 commented on src/components/ErrorAlert/styles.ts
>    border: 1px solid
ok

2024-10-10 13:01 UTC, Angelbt12 commented on src/components/ErrorAlert/config.ts
>      defaultError: "Existe un error sin evaluar",
ok

2024-10-24 13:06 UTC, carin91 approved these changes

2024-10-24 13:06 UTC, merged