jg/cb1/Create-visual-version-of-C001
selsa-inube/crediboard pull request #2
Opened 2024-04-09 08:31 UTC by novadeveloper14

Create the “Tarjeta resumen” component C001.

This not include the functionality of this card.

This task includes the storybook for the component

The props are handled as they appear in the task Include the props with the information of the request in C001 cb5

2024-04-09 14:09 UTC, Andresbl123 commented on src/components/cards/SummaryCard/index.tsx
> +            {currencyFormat(value)}
Teniendo en cuenta el comentario de la función `currencyFormat` y aquí asemos la validación con una ternaria: `<Text type="label" >
            {value === 0 ? "$ 0" : currencyFormat(value)}
          </Text>`, con esto si el `value` es cero, no cargamos el js de la función `currencyFormat` y hacemos el formateo ahí mismo.

2024-04-09 14:09 UTC, Andresbl123 commented on src/mocks/utils/formatData/currency.ts
> +  if (price === 0) {
podríamos negocias este enfoque, podríamos quitar esta validación, y dejar que  `currencyFormat`  solo realice el formatear el precio como moneda de lo que pasemos y solo la ejecutemos cuando queremos realizar dicho formateo.

2024-04-09 21:10 UTC, Andresbl123 approved these changes

2024-04-10 11:05 UTC, carin91 requested changes

2024-04-10 11:05 UTC, carin91 commented on src/mocks/utils/formatData/currency.ts
> +const currencyFormat = (price: number): string => {
Relocate this util to @utils, you just assumed that the folder @mocks will be ignored/deleted for production, therefore, this folder must contain information that will be given by the server.

2024-04-10 11:05 UTC, carin91 commented on src/mocks/utils/formatData/text.ts
> +const truncateTextToMaxLength = (text: string, maxLength = 50) => {
Relocate this util to https://github.com/utils, you just assumed that the folder @Mocks will be ignored/deleted for production, therefore, this folder must contain information that will be given by the server.

2024-04-10 11:05 UTC, carin91 commented on src/pages/login/interface.tsx
> -            <Text as="h1" type="headline" size="large">
Avoid the edition of components not related to the task. Instead, if you want a change, you could create an issue and it will be eventually adjusted.

2024-04-10 11:05 UTC, carin91 commented on src/pages/login/outlets/CheckingCredentials/interface.tsx
> -        <Text type="title" size="large" textAlign="center">
Avoid the edition of components not related to the task. Instead, if you want a change, you could create an issue and it will be eventually adjusted.

2024-04-10 11:32 UTC, carin91 requested changes

2024-04-10 11:32 UTC, carin91 commented on src/components/cards/SummaryCard/styles.ts
> +  flex-direction: column;
The summary cards are buttons which redirects to requests/:id_request to view the details of them.
Therefore, the summary cards must have a "call to action" for the functionary, i would bet for a &:hover with cursor pointer.

2024-04-10 11:34 UTC, carin91 requested changes

2024-04-10 11:34 UTC, carin91 commented on .storybook/preview-head.html
>  <link rel="preconnect" href="https://fonts.googleapis.com" />
Integrate the main changes before the next review.

2024-04-11 09:11 UTC, carin91 approved these changes

2024-04-11 09:11 UTC, merged