At/cb246/minors 7
selsa-inube/crediboard pull request #204
Opened 2024-10-23 17:39 UTC by Angelbt12

https://inube.atlassian.net/jira/software/projects/CB/boards/20?selectedIssue=CB-246

2024-10-24 22:17 UTC, SelsaErojas requested changes
you should see this error in the requirements section
![image](https://github.com/user-attachments/assets/2f242f18-201c-448c-8a86-8118a76b416d)

2024-10-24 22:17 UTC, SelsaErojas commented on src/pages/board/outlets/financialReporting/CommercialManagement/index.tsx
>  import { ExtraordinaryPaymentModal } from "@src/pages/prospect/components/ExtraordinaryPaymentModal";
Adjust the import aliases using the alias for components and adjust order of the import.

2024-10-24 22:17 UTC, SelsaErojas commented on src/pages/board/outlets/financialReporting/management/styles.ts
>    &::-webkit-scrollbar-thumb {
Adjust to the inubekit library

2024-10-25 13:04 UTC, Angelbt12 commented on src/pages/board/outlets/financialReporting/management/styles.ts
>    &::-webkit-scrollbar-thumb {
This file was already approved a long time ago, I just had to adjust the width of the scroll

2024-10-28 14:50 UTC, SelsaErojas requested changes

2024-10-28 14:50 UTC, SelsaErojas commented on src/pages/board/outlets/financialReporting/management/styles.ts
>    &::-webkit-scrollbar-thumb {
Do not use @inube/design-system

2024-10-28 14:50 UTC, SelsaErojas commented on src/pages/board/outlets/financialReporting/CommercialManagement/index.tsx
> +import { formatPrimaryDate } from "@utils/formatData/date";
Adjust the import aliases using the alias for components and adjust order of the import. (line 38 and line 40)

2024-10-28 17:25 UTC, SelsaErojas approved these changes
Funtional

2024-10-30 10:30 UTC, carin91 approved these changes

2024-10-30 13:41 UTC, merged