At/cb247/minors 8
selsa-inube/crediboard pull request #205
Opened 2024-10-24 12:22 UTC by Angelbt12

https://inube.atlassian.net/jira/software/projects/CB/boards/20?selectedIssue=CB-247

2024-10-24 22:02 UTC, SelsaErojas requested changes

2024-10-24 22:02 UTC, SelsaErojas commented on src/components/modals/ReciprocityModal/index.tsx
>  import { currencyFormat } from "@src/utils/formatData/currency";
Adjust the import aliases using the alias for components and adjust order of the import.

2024-10-24 22:02 UTC, SelsaErojas commented on src/pages/board/outlets/financialReporting/CommercialManagement/index.tsx
>              portalId="portal"
Adjust the import aliases using the alias for components and adjust order of the import.

2024-10-28 15:40 UTC, SelsaErojas requested changes

2024-10-28 15:40 UTC, SelsaErojas commented on src/pages/board/outlets/financialReporting/CommercialManagement/index.tsx
> -            portalId="portal"
¿why change name of portal?
![image](https://github.com/user-attachments/assets/4b274a61-2cd9-43d6-a1b7-bc167fa7e531)

2024-10-28 17:34 UTC, SelsaErojas approved these changes
Functional

2024-10-30 10:36 UTC, carin91 approved these changes

2024-10-30 10:36 UTC, carin91 commented on src/components/modals/CreditLimit/index.tsx
> +              El menor de los anteriores es su cupo <strong>máximo</strong>{" "}
Relocate it into a config file...
I would use a jsx script to achieve this.

2024-10-30 10:36 UTC, carin91 commented on src/components/modals/PaymentCapacityModal/interface.tsx
> +              Monto máximo calculado para una cuota de
Relocate this into the config file

2024-10-30 16:28 UTC, merged