implement extraordinary installments step
selsa-inube/crediboard pull request #206
Opened 2024-10-24 15:40 UTC by SelsaErojas

implement extraordinary installments step

2024-10-26 06:10 UTC, novadeveloper14 commented
The title of the PR should contain the task code, in this case cb252

2024-10-26 06:34 UTC, novadeveloper14 requested changes

2024-10-26 06:34 UTC, novadeveloper14 commented on package-lock.json
Is there any reason to update package-lock.json?

2024-10-26 06:34 UTC, novadeveloper14 commented on src/pages/add-prospect/interface.tsx
>  import { useMediaQuery } from "@inubekit/hooks";
In the project we are organizing the imports in the following way:

External imports (from inubekit, icons, hooks... any library external to the project)
////////space////////
Internal imports with aliases (imports with `@alias` currently the ones we have in the vite.config.ts file)
///////space//////
Internal imports without aliases (such as "./steps/extraordinaryInstallments")

This must be applied to all files that are created or modified. Whenever you see a file that does not comply with this rule, please modify it.

2024-10-26 06:34 UTC, novadeveloper14 commented on src/pages/add-prospect/interface.tsx
> +          currentStepsNumber.id === stepsAddProspect.specialFertilizers.id && (
Let's modify the id specialFertilizers to extraordinaryInstallments

2024-10-26 06:34 UTC, novadeveloper14 commented on src/pages/add-prospect/steps/extraordinaryInstallments/config/types.ts
These files where the texts are configured are being left in this path: src\config\pages, which could create a new folder called add-prospect (which represents the assisted)

2024-10-26 06:34 UTC, novadeveloper14 commented on src/pages/add-prospect/steps/extraordinaryInstallments/index.tsx
> +export const ExtraordinaryInstallments = (
We are leaving the components as function(), not arrow type functions.

2024-10-26 06:34 UTC, novadeveloper14 commented on src/pages/add-prospect/steps/extraordinaryInstallments/index.tsx
> +  const openAddSeriesModal = () => {
you could refactor these two functions with a toggle:

```
const toggleAddSeriesModal = () => {
  setAddSeriesModalOpen(!isAddSeriesModalOpen);
};
```

2024-10-26 06:34 UTC, novadeveloper14 commented on src/pages/add-prospect/steps/extraordinaryInstallments/index.tsx
> +              type="button"
The button already has some of the parameters that you set by default, determine which ones they are and remove them from the code:

https://github.com/selsa-inube/inubekit-button/blob/main/src/Button/index.tsx

2024-10-26 06:34 UTC, novadeveloper14 commented on src/pages/add-prospect/steps/extraordinaryInstallments/index.tsx
> +              <Text size="large" type="label" appearance="gray" weight="bold">
The Text already has some of the parameters that you set by default, determine which ones they are and remove them from the code:

https://github.com/selsa-inube/inubekit-text/blob/main/src/Text/index.tsx

Check this in other component texts

2024-10-26 06:34 UTC, novadeveloper14 commented on src/pages/add-prospect/steps/extraordinaryInstallments/index.tsx
> +          title="Nueva serie"
All Spanish text displayed on the screen should go in a configuration file

2024-10-29 15:56 UTC, SelsaErojas commented on src/pages/add-prospect/interface.tsx
> +          currentStepsNumber.id === stepsAddProspect.specialFertilizers.id && (
resolved

2024-10-29 15:56 UTC, SelsaErojas commented on src/pages/add-prospect/steps/extraordinaryInstallments/config/types.ts
resolved

2024-10-29 15:56 UTC, SelsaErojas commented on src/pages/add-prospect/steps/extraordinaryInstallments/index.tsx
> +              type="button"
resolved

2024-10-29 15:56 UTC, SelsaErojas commented on src/pages/add-prospect/steps/extraordinaryInstallments/index.tsx
> +              <Text size="large" type="label" appearance="gray" weight="bold">
resolved

2024-10-29 15:56 UTC, SelsaErojas commented on src/pages/add-prospect/steps/extraordinaryInstallments/index.tsx
> +          title="Nueva serie"
resolved

2024-10-29 15:56 UTC, SelsaErojas commented on src/pages/add-prospect/steps/extraordinaryInstallments/index.tsx
> +  const openAddSeriesModal = () => {
resolved

2024-10-29 15:56 UTC, SelsaErojas commented on src/pages/add-prospect/interface.tsx
>  import { useMediaQuery } from "@inubekit/hooks";
ok

2024-10-29 19:35 UTC, novadeveloper14 approved these changes

2024-10-31 21:39 UTC, carin91 approved these changes

2024-11-07 20:33 UTC, merged