cb250 implement money destination step
selsa-inube/crediboard pull request #209
Opened 2024-10-26 02:31 UTC by novadeveloper14

2024-10-28 14:45 UTC, Brandonz07 requested changes
You need to create the mock, as shown in the image

![image](https://github.com/user-attachments/assets/e0e9a8f7-3353-446d-bd12-6bcf36623a00)

2024-10-28 16:47 UTC, Brandonz07 commented on src/pages/add-prospect/steps/MoneyDestination/index.tsx
> +import { useEffect } from "react";
Adjust imports, unify useState and useEffect

2024-10-28 16:48 UTC, Brandonz07 commented on src/pages/add-prospect/steps/MoneyDestination/interface.tsx
> +import { IMoneyDestination } from "@src/services/types";
only services/types

2024-10-28 16:48 UTC, Brandonz07 commented on src/components/cards/MoneyDestinationCard/index.tsx
> +import { IconType } from "react-icons";
Adjust imports

2024-10-30 10:50 UTC, carin91 approved these changes

2024-10-30 10:50 UTC, merged