cb255 implement the loan conditions step 8
selsa-inube/crediboard pull request #210
Opened 2024-10-28 14:08 UTC by Brandonz07

2024-10-29 15:35 UTC, SelsaErojas requested changes
You should check the option because you see the same description
![image](https://github.com/user-attachments/assets/83d0d5e4-f165-4c3f-b657-d09d6b46eb8a)

2024-10-29 15:35 UTC, SelsaErojas commented on src/pages/add-prospect/steps/loanCondition/config.ts
>      title2: "¿Tiene un plazo máximo para el pago?",
you should change this names by others for example:
in case of the title1 you can use QuotaCap and case of the title2 you can use MaximumTerm
QuotaCapTittle
QuotaCapLabel
QuotaCapPlaceholder
the same for the option names of the toggle

2024-10-29 22:02 UTC, SelsaErojas approved these changes
Functional

2024-10-31 21:38 UTC, carin91 approved these changes

2024-10-31 21:38 UTC, carin91 commented on src/pages/add-prospect/steps/loanCondition/index.tsx
> +                placeholder={loanData.quotaCapPlaceholder}
pass the data through an util which render the amount with currency format

2024-11-01 18:32 UTC, merged