cb256 Implement the loan amount step 9
selsa-inube/crediboard pull request #211
Opened 2024-10-29 16:01 UTC by Brandonz07

![image](https://github.com/user-attachments/assets/eb585d67-611d-4ca7-83d9-105fd821b061)

2024-10-30 19:43 UTC, novadeveloper14 commented
solve conflicts

2024-10-30 19:50 UTC, novadeveloper14 requested changes

2024-10-30 19:50 UTC, novadeveloper14 commented on src/components/data/Fieldset/styles.ts
> +  overflow-x: ${({ $hasOverflow }) => $hasOverflow && "visible"};
the app is breaking

![image](https://github.com/user-attachments/assets/1b80ac61-2ed2-47a7-b3f3-a93f6cb5eeea)

2024-10-30 19:50 UTC, novadeveloper14 commented on src/pages/add-prospect/interface.tsx
>  interface StepDetails {
Any other interface or type other than the component's props should go in a type.ts

2024-10-30 19:50 UTC, novadeveloper14 commented on src/pages/add-prospect/interface.tsx
In the project we are organizing the imports in the following way:

External imports (from inubekit, icons, hooks... any library external to the project)
////////space////////
Internal imports with aliases (imports with @alias currently the ones we have in the vite.config.ts file)
///////space//////
Internal imports without aliases (such as "./steps/extraordinaryInstallments")

This must be applied to all files that are created or modified. Whenever you see a file that does not comply with this rule, please modify it.

2024-10-30 19:50 UTC, novadeveloper14 commented on src/pages/add-prospect/interface.tsx
> +  const planData = [
This should go in a configuration file or be mock simulated. evaluate with camilo

2024-10-30 19:50 UTC, novadeveloper14 commented on src/pages/add-prospect/steps/loanAmount/index.tsx
> +import { useState } from "react";
In the project we are organizing the imports in the following way:

External imports (from inubekit, icons, hooks... any library external to the project)
////////space////////
Internal imports with aliases (imports with @alias currently the ones we have in the vite.config.ts file)
///////space//////
Internal imports without aliases (such as "./steps/extraordinaryInstallments")

This must be applied to all files that are created or modified. Whenever you see a file that does not comply with this rule, please modify it.

2024-11-02 07:24 UTC, novadeveloper14 approved these changes

2024-11-13 13:45 UTC, carin91 approved these changes

2024-11-13 13:45 UTC, carin91 commented on src/mocks/add-prospect/request-value/requesvalue.mock.ts
> +export const mockRequestValue: IRequestVelue[] = [
change the name to mockPaymentChannel

2024-11-13 13:45 UTC, carin91 commented on src/pages/add-prospect/steps/loanAmount/index.tsx
> +            fullwidth
avoid coercion

2024-11-13 14:32 UTC, merged