cb271 Create the routs for edit-prospect
selsa-inube/crediboard pull request #229
Opened 2024-12-11 23:44 UTC by Brandonz07

2024-12-19 21:44 UTC, carin91 requested changes

2024-12-19 21:44 UTC, carin91 commented on src/pages/addProspect/index.tsx
> +    if (id) {
This code is returned by the backend service and does not represent the client's identification. I would consider registering this deviation for now, so it can be addressed during the integration with iProspect

2024-12-19 21:44 UTC, carin91 commented on src/components/inputs/SummaryOnProspect/index.tsx
>  import { Icon } from "@inubekit/icon";
The name/location combination is not appropriate. I would either (1) rename the component to make it a generic component or (2) relocate it as a prospect component in the appropriate location.

2024-12-19 21:44 UTC, carin91 commented on src/pages/board/outlets/financialReporting/CommercialManagement/index.tsx
> +
Remove the extra space that is breaking the standard.

2024-12-19 21:44 UTC, carin91 commented on src/pages/prospect/components/CreditProspect/index.tsx
> +  showMenu: () => void;
Relocate the required props at the beginning

2024-12-19 21:44 UTC, carin91 commented on src/pages/prospect/components/CreditProspect/index.tsx
> +    children = <Stack />,
I'm not sure about that. The React children are passed differently from other props. Therefore, I would prefer to delete this line, even if it means using coercion.

2024-12-19 21:44 UTC, carin91 commented on src/pages/prospect/components/CreditProspect/index.tsx
> +  const [updatedChildren, setUpdatedChildren] = useState(children);
Refactor the component to avoid the creation of this state.

2025-01-02 15:49 UTC, carin91 requested changes

2025-01-02 15:49 UTC, carin91 commented on src/components/cards/cardValues/index.tsx
> +            icon={<MdOutlineEdit />}
Why is the OutlineEdit icon used as the default? Is this component intended to support only this icon?

2025-01-02 15:49 UTC, carin91 commented on src/pages/addProspect/index.tsx
> +    navigate(`/edit-prospect/999990`);
The number of prospects will be returned by the API providing the create-prospect service. Therefore, I would prefer to refactor the solution as follows:

1. Create a mock file to generate this code.
2. Since the service may take time to respond due to the financial algorithm, include a 1-second delay before returning the code.
3. Use 999990 as the mock code, consistent with the current implementation.

2025-01-02 15:49 UTC, carin91 commented on src/pages/board/outlets/financialReporting/CommercialManagement/config/config.tsx
> +        amount: "5000000",
This value will be provided by the backend service and should not be placed in a configuration file. Instead, it should be included in the prospect mock. Additionally, the ComercialManagement component should be refactored to render this amount dynamically from the backend service.

2025-01-02 15:49 UTC, carin91 commented on src/pages/board/outlets/financialReporting/CommercialManagement/config/config.tsx
> +        operation:"-"
Verify the setting of the (-) (+) (=) signs, as well as the divider, considering the previous comment

2025-01-02 15:49 UTC, carin91 commented on src/pages/board/outlets/financialReporting/CommercialManagement/index.tsx
>  export const ComercialManagement = (props: ComercialManagementProps) => {
Verify the last version of the component, in the mockups was included a card with a (+) sign.
![image](https://github.com/user-attachments/assets/d346c672-391b-49a7-948d-2258ee4d9a7f)

2025-01-02 15:49 UTC, carin91 commented on src/pages/board/outlets/financialReporting/CommercialManagement/index.tsx
> +  const { data, print, isPrint } = props;
Assign default values to optional props (e.g., isPrint = false) to prevent type coercion.

2025-01-02 15:49 UTC, carin91 commented on src/pages/board/outlets/financialReporting/CommercialManagement/index.tsx
>    const { id } = useParams();
Change the name of the parameter in the routes. The proper name should be either prospectCode, or creditRequestCode, depending on the case. A credit request contains both prospectCode and creditRequestCode, which can be different but unique. In cases where the information to be rendered is the prospect's details, the prospectCode should be used.

Additionally, for the extended card, the endpoint requires the creditRequestCode as a parameter. For the extended card, the prospectCode will be part of the JSON response of the master entity. For the edit-prospect endpoint, the parameter in the URL will be prospectCode. Therefore, I would suggest the following:

1. Change the name of this prop to prospectCode.
2. Pass it as a prop to the creditProspect component.
3. For the extended card, this prop will be passed from the body of the master entity.
4. For the edit-prospect endpoint, this prop will be passed using useParams.

2025-01-02 15:49 UTC, carin91 commented on src/pages/editProspect/config.ts
> +    name: "Camilo Alberto Rincón Jaramillo",
the name of the client as other information should not be included in a config file.

2025-01-27 23:12 UTC, SelsaErojas requested changes
According to figma, it is necessary to add the options for extra payments and collected obligations
![image](https://github.com/user-attachments/assets/e3c5ae9a-9037-4db3-8fde-08bdeceba0f2)

2025-01-30 21:04 UTC, SelsaErojas approved these changes
Funtional!

2025-01-30 21:11 UTC, carin91 approved these changes

2025-01-30 21:13 UTC, merged