Create modal in CU030
selsa-inube/crediboard pull request #38
Opened 2024-05-30 06:44 UTC by novadeveloper14

The modal that appears in operation CU030 was carried out, which is when the reject button is clicked in the financialReporting outlet.

![image](https://github.com/selsa-inube/crediboard/assets/87447257/71a83552-f06b-4c49-b43d-cb4f78071a52)

points to consider:

- The modal component was configured to be general and accept any type of configuration related to the textarea

- The textarea component of the current version of the design-system library does not allow removing the resize

- The component receives a maxLength, which is the characters maximum that the component receives, which cannot be removed, so the modal was assigned to have this value be 200 characters by default.

- when the number of current characters in the textarea is equal to 0 or is greater than the maxLength the confirm button becomes disabled

2024-05-30 15:42 UTC, LinconOssa approved these changes
Meets the requirements.

2024-06-04 09:38 UTC, carin91 requested changes

2024-06-04 09:38 UTC, carin91 commented on src/components/layout/ContainerSections/index.tsx
> +  const [showRejectModal, setShowRejectModal] = useState(false);
Change the spelling of the word.
Reject = Rechazar
Rejection = Rechazo

2024-06-04 09:38 UTC, carin91 commented on src/components/modals/TextAreaModal/index.tsx
> +import {
Every component must have its storybook. Implement the storybook for this component.

2024-06-04 09:38 UTC, carin91 commented on src/components/modals/TextAreaModal/index.tsx
> +    <Blanket>
Is it a form or not? it has inputs (type="textArea") as the submit button. Why avoid the form tag of html? The submit will also trigger a post request, therefore, I would use the form tag.

Currently, we are using Formik in several apps (such as PortalClientesFondecom and iSetting Portal), so, I would use Formik too.

2024-06-12 10:07 UTC, carin91 commented on src/components/modals/TextAreaModal/index.tsx
> +import {
This task is still pending.

(1) The storybook is not working. To adjust that you need to create a router as decoration of the storybook.
(2) Change the location of the storybook.
![image](https://github.com/selsa-inube/crediboard/assets/123512032/6e9898c0-9c35-4318-a0f4-dee8e2f344e0)

  title: "components/layouts/ContainerSections",

2024-06-12 10:11 UTC, carin91 approved these changes
The component has a little difference with the wireframes, verify that this component is implemented as required.

![image](https://github.com/selsa-inube/crediboard/assets/123512032/725c9c7a-76c8-4be4-ac7e-78e8550f7044)

(2) I understand that this is a mistake of the designer, however, avoid errors in spelling and gramatics.

Error: "Motivo del Rechazo"
Correct: "Motivo del rechazo."

2024-06-12 15:11 UTC, merged