Create mobile version layout solicitud
selsa-inube/crediboard pull request #43
Opened 2024-06-14 22:37 UTC by Andresbl123

The mobile version of the application is created, where the presentation of each of the sections that are part of this page is adjusted, this PR is limited only to the layout, so for the moment in terms of functionality some adjustments still need to be made,

2024-07-03 08:47 UTC, novadeveloper14 requested changes

2024-07-03 08:47 UTC, novadeveloper14 commented on src/pages/board/outlets/financialReporting/index.tsx
the component is getting corrupted in its desktop version

![image](https://github.com/selsa-inube/crediboard/assets/87447257/65c9fa68-0059-4a9b-86cb-4eb1472dff75)
![image](https://github.com/selsa-inube/crediboard/assets/87447257/d7683ddb-d007-4579-a4a5-d26f9a2ab8a2)

2024-07-03 08:47 UTC, novadeveloper14 commented on src/pages/board/outlets/financialReporting/index.tsx
It seems that from a point here there should be a separation
![image](https://github.com/selsa-inube/crediboard/assets/87447257/70859fb6-f3aa-4a3b-bee0-61eb7b4fcf43)

2024-07-03 16:12 UTC, Andresbl123 commented on src/pages/board/outlets/financialReporting/index.tsx
resolved

2024-07-03 16:48 UTC, Andresbl123 commented on src/pages/board/outlets/financialReporting/index.tsx
resolved

2024-07-04 06:28 UTC, novadeveloper14 approved these changes

2024-07-04 06:33 UTC, novadeveloper14 requested changes
Some size or type of the text components of this card and margin/padding change in its mobile version, please solve so that the requirement of the cb66 task can be met

App:
![image](https://github.com/selsa-inube/crediboard/assets/87447257/dc39df7e-91f5-4c8e-902b-fec797ad6982)

Figma:
![image](https://github.com/selsa-inube/crediboard/assets/87447257/bfa45943-764b-4ac5-93e0-7152a6c765b9)

![image](https://github.com/selsa-inube/crediboard/assets/87447257/ff2eef9d-85a0-4f6c-b284-4c187865ae87)

2024-07-04 06:38 UTC, novadeveloper14 commented
Please, if the PR solves more tasks besides the main branch, please let me know in the description of the PR.

2024-07-04 06:47 UTC, novadeveloper14 requested changes
comment related to task: cb64

The ToDo component already has its mobile version available, so we should pass the isMobile variable to it from the index.tsx of FinancialReporting:

![image](https://github.com/selsa-inube/crediboard/assets/87447257/7994d09f-e7f8-4b56-8568-a8dab5ba2dcb)

After this, adjust the separation of the cards with the ends of the screen since it is becoming a little out of adjustment.

App:
![image](https://github.com/selsa-inube/crediboard/assets/87447257/1ef0650b-c6db-4560-812a-0e2d98d2185c)

Figma:

![image](https://github.com/selsa-inube/crediboard/assets/87447257/62bee83f-e227-4321-86a7-46ee1e3ba3bb)

2024-07-08 15:20 UTC, novadeveloper14 approved these changes

2024-07-10 08:46 UTC, carin91 approved these changes

2024-07-11 15:40 UTC, merged