Create visual version `<ContainerSections />`
selsa-inube/crediboard pull request #5
Opened 2024-04-10 17:31 UTC by Andresbl123

Create the layout component, which accepts props of type `JSX.Element | JSX.Element[];`, to render components under a layout.

2024-04-11 05:52 UTC, novadeveloper14 requested changes

2024-04-11 05:52 UTC, novadeveloper14 commented on src/components/layout/ContainerSections/ContainerSections.stories.tsx
> +  title: "components/layout/ContainerSections",
Let's put "layouts/ContainerSections" so that 2 layout sections are not created:

![image](https://github.com/selsa-inube/crediboard/assets/87447257/3be1f6f9-8cb4-4554-9a85-a93a9ebc77f0)

2024-04-11 05:52 UTC, novadeveloper14 commented on src/components/layout/ContainerSections/index.tsx
> +import { MdArrowBack } from "react-icons/md";
Adjust to the standard for imports in this team:
(1) External components
(space)
(2) Internal components which use aliases
(space)
(3) Internal component without aliases

example:

![image](https://github.com/selsa-inube/crediboard/assets/87447257/b5a270de-48fa-4680-bcff-99e1b48a495e)

2024-04-11 05:52 UTC, novadeveloper14 commented on src/components/layout/ContainerSections/styles.ts
> +  margin: 0px;
use ${inube.spacing.s0}

2024-04-11 05:52 UTC, novadeveloper14 commented on src/components/layout/ContainerSections/index.tsx
> +          <Stack gap="16px">
gap={inube.spacing.s200}

2024-04-11 05:52 UTC, novadeveloper14 commented on src/components/layout/ContainerSections/index.tsx
> +          <Stack gap="16px">
use gap={inube.spacing.s200}

2024-04-11 05:52 UTC, novadeveloper14 commented on src/components/layout/ContainerSections/index.tsx
> +        <Stack justifyContent="end" gap="32px">
use gap={inube.spacing.s400}

2024-04-11 05:52 UTC, novadeveloper14 commented on src/components/layout/ContainerSections/ContainerSections.stories.tsx
> +import { Meta, StoryObj } from "@storybook/react";
Adjust to the standard for imports in this team:
(1) External components
(space)
(2) Internal components which use aliases
(space)
(3) Internal component without aliases

2024-04-11 05:52 UTC, novadeveloper14 commented on src/components/layout/ContainerSections/styles.ts
> +export const StyledHorizontalRule = styled.hr`
let's put "border: none"; to remove the black line to the left of the hr

before:

![image](https://github.com/selsa-inube/crediboard/assets/87447257/a9e531cc-026c-45a1-8611-e7e5e4b3cb22)

then with 2px width:

![image](https://github.com/selsa-inube/crediboard/assets/87447257/951d7af4-182f-4d71-b79e-6be1c5ba1ca2)

2024-04-11 17:07 UTC, Andresbl123 commented on src/components/layout/ContainerSections/ContainerSections.stories.tsx
> +  title: "components/layout/ContainerSections",
resulto

2024-04-11 17:07 UTC, Andresbl123 commented on src/components/layout/ContainerSections/index.tsx
> +import { MdArrowBack } from "react-icons/md";
resuelto

2024-04-11 17:07 UTC, Andresbl123 commented on src/components/layout/ContainerSections/styles.ts
> +  margin: 0px;
resuelto

2024-04-11 17:07 UTC, Andresbl123 commented on src/components/layout/ContainerSections/index.tsx
> +          <Stack gap="16px">
resuelto

2024-04-11 17:07 UTC, Andresbl123 commented on src/components/layout/ContainerSections/index.tsx
> +        <Stack justifyContent="end" gap="32px">
resuelto

2024-04-11 17:07 UTC, Andresbl123 commented on src/components/layout/ContainerSections/index.tsx
> +        <Stack justifyContent="start" margin="s0 s0 s250 s0">
resuelto

2024-04-11 17:27 UTC, Andresbl123 commented on src/components/layout/ContainerSections/styles.ts
> +export const StyledHorizontalRule = styled.hr`
resuelto

2024-04-11 17:27 UTC, Andresbl123 commented on src/components/layout/ContainerSections/styles.ts
> +export const StyledHorizontalRule = styled.hr`
resuelto

2024-04-11 17:27 UTC, Andresbl123 commented on src/components/layout/ContainerSections/ContainerSections.stories.tsx
> +import { Meta, StoryObj } from "@storybook/react";
resuelto

2024-04-11 20:13 UTC, novadeveloper14 approved these changes

2024-04-15 11:17 UTC, carin91 approved these changes

2024-04-15 11:17 UTC, merged