Implement the case of use related to "more details" in requests
selsa-inube/crediboard pull request #51
Opened 2024-06-28 11:58 UTC by novadeveloper14

2024-07-02 00:14 UTC, Andresbl123 approved these changes
Cumple requerimientos

2024-07-04 12:23 UTC, carin91 requested changes
The more details button should render "more details" about the requisit. Therefore, this is not a form, is a field which presents the date and a not editable text which was delivered by the backend.

Refactor considering it.

2024-07-10 09:51 UTC, carin91 requested changes
Adjust the modal considering these:
(1) The date format is dd/Mmm/yyy, where the month should be in letters (Caps on first)
(2) Delete the number of characters validation on the text field area
![image](https://github.com/selsa-inube/crediboard/assets/123512032/52e735bc-4c43-44dd-ade8-5d36dda80dc6)
(3) The Format for the date is different, is not disable, not gray.  (This does not mean that the user could edit the date)
![image](https://github.com/selsa-inube/crediboard/assets/123512032/58c4095e-44a6-4cd9-bfe6-4ecfb5a95173)

2024-07-17 10:06 UTC, carin91 approved these changes

2024-07-17 10:10 UTC, carin91 approved these changes

2024-07-17 10:11 UTC, merged