implement imprimir credit products
selsa-inube/crediboard pull request #56
Opened 2024-07-03 22:41 UTC by Andresbl123

Implement “imprimir” operation for the credit products

2024-07-25 23:01 UTC, Angelbt12 approved these changes

2024-07-26 01:33 UTC, carin91 requested changes

2024-07-26 01:33 UTC, carin91 commented on src/utils/pdf/generetePDF.ts
> +      const imgHeight = (canvas.height * imgWidth) / canvas.width;
Could you verify the scaling of the img?
What happens if the table has 3 or 4 columns?
The user needs to hold consistency between sizes.

2024-07-29 15:54 UTC, Andresbl123 commented on src/utils/pdf/generetePDF.ts
> +      const imgHeight = (canvas.height * imgWidth) / canvas.width;
resolve 
![image](https://github.com/user-attachments/assets/c3dab1ca-9cda-4103-b3c3-f2ec1b008cf0)

2024-07-29 20:06 UTC, carin91 approved these changes

2024-07-29 20:07 UTC, merged