At/cb 80 implement unevaluated error
selsa-inube/crediboard pull request #57
Opened 2024-07-05 14:50 UTC by Angelbt12

2024-07-05 22:20 UTC, Andresbl123 commented on src/components/ErrorAlert/index.tsx
> +const ErrorAlert: React.FC<ErrorAlertProps> = ({ errorKey, message }) => {
Este tipado  ya no es recomendado, por estándar  en el proyecto lo manejamos así ; `const Component = (props: interface) => {
  const { desesctructuraciión de las pros } = props
};`  Esto permite que el tipado del componente o lo que devuelve la función sea  `JSX.Element`

2024-07-05 22:20 UTC, Andresbl123 commented on src/components/ErrorAlert/index.tsx
> +  React.useEffect(() => {
No creo que se necesite un `useEffect`, y en este no sería el uso adecuado de este hook, ya que es el componente padre quien decide si muestra o este componente

2024-07-05 22:20 UTC, Andresbl123 commented on src/components/ErrorAlert/index.tsx
> +  const [visible, setVisible] = React.useState(errorKey);
no creo que sea necesario este estado, lo que sugiero es que `errorKey`, sea una función y sea desde el padre que se maneje estos comportamientos

2024-07-05 22:20 UTC, Andresbl123 commented on src/components/ErrorAlert/index.tsx
> +  if (!visible) return null;
un componente por buena practica no debería retornar un null esta línea sobra

2024-07-05 22:20 UTC, Andresbl123 commented on src/components/ErrorAlert/styles.ts
> +export const AlertContainer = styled.div`
Validar que en el sistema de diseño, hay un componente `<Icon />`, implementarlo y validar que otro componente sirve, para poder depurar estos estilos, que pienso que en su mayoría son innecesarios

2024-07-05 22:23 UTC, Andresbl123 commented on src/components/ErrorAlert/ErrorAlert.stories.tsx
> +export default {
Tener en cuenta el estándar que se maneja en el proyecto, que se alinea a la documentación de storybook, se puede guiar por los ejemplos ya implementados en el proyecto o por la documentación de storybook  
![image](https://github.com/selsa-inube/crediboard/assets/74839801/cb1571d6-ad8f-4598-b6bc-6f899192672f)

2024-07-08 12:05 UTC, Angelbt12 commented on src/components/ErrorAlert/ErrorAlert.stories.tsx
> +export const CustomMessage = Template.bind({});
ok vale

2024-07-08 12:06 UTC, Angelbt12 commented on src/components/ErrorAlert/index.tsx
> +const ErrorAlert: React.FC<ErrorAlertProps> = ({ errorKey, message }) => {
ok

2024-07-08 12:09 UTC, Angelbt12 commented on src/components/ErrorAlert/index.tsx
> +  React.useEffect(() => {
ok vale

2024-07-08 12:11 UTC, Angelbt12 commented on src/components/ErrorAlert/index.tsx
> +  const [visible, setVisible] = React.useState(errorKey);
ok

2024-07-08 12:49 UTC, Angelbt12 commented on src/components/ErrorAlert/index.tsx
> +  if (!visible) return null;
ok

2024-07-08 13:13 UTC, Angelbt12 commented on src/components/ErrorAlert/styles.ts
> +export const AlertContainer = styled.div`
ok

2024-07-08 13:56 UTC, Angelbt12 commented on src/components/ErrorAlert/ErrorAlert.stories.tsx
> +export default {
vale ya lo arreglo, ya miro y leo la documentación gracias

2024-07-08 14:35 UTC, Andresbl123 commented on src/components/ErrorAlert/index.tsx
ajustar espaciados y alineación del componente, según diseño de figma 
![image](https://github.com/selsa-inube/crediboard/assets/74839801/8d43c843-84b6-41f6-90bc-f2f7bec7e7e1)

2024-07-08 14:35 UTC, Andresbl123 commented on src/components/ErrorAlert/index.tsx
> +      <CloseButton onClick={handleClose}>
esto no me queda muy , claro, pero según veo el diseño, se usan solo iconos, si este es el '"boton" de cerrar, seria mejor que fuera icono, ,tener en cuenta el comentario del estado, porqué sigo pensando que el estado es innecesario ya sea para un `button` o para un `icono`

2024-07-08 20:03 UTC, Angelbt12 commented on src/components/ErrorAlert/index.tsx
ok

2024-07-08 20:13 UTC, Angelbt12 commented on src/components/ErrorAlert/index.tsx
> +      <CloseButton onClick={handleClose}>
aaa ok vale si te entiendo ya lo arreglo

2024-07-09 13:32 UTC, Andresbl123 reviewed
Realizar la descripción de la PR

2024-07-09 13:32 UTC, Andresbl123 commented on src/components/ErrorAlert/index.tsx
> +  errorKey: boolean;
ya que se agrego la props `onClose`, la props `errorKey` no es necesaria

2024-07-09 13:32 UTC, Andresbl123 commented on src/components/ErrorAlert/index.tsx
> +  const [visible, setVisible] = useState(errorKey);
este estado no es necesario ya con la props de función el componente padre puede controlar esto

2024-07-09 13:32 UTC, Andresbl123 commented on src/components/ErrorAlert/index.tsx
> +  const handleClose = () => {
esto de acuerdo a quitar el estado, ya no sería necesario

2024-07-09 13:32 UTC, Andresbl123 commented on src/components/ErrorAlert/index.tsx
> +    <AlertContainer style={{ display: visible ? "flex" : "none" }}>
los estilos para un styeled component,,  se hacen desde el archivo de `styles.ts`, los estilos desde aquí lo debemos evitar en lo posible

2024-07-09 13:32 UTC, Andresbl123 commented on src/components/ErrorAlert/index.tsx
> +export default ErrorAlert;
utilicemos exportaciones nombradas

2024-07-09 13:32 UTC, Andresbl123 commented on src/components/ErrorAlert/index.tsx
> +export default ErrorAlert;
utilicemos exportaciones nombradas

2024-07-09 13:32 UTC, Andresbl123 commented on src/components/ErrorAlert/styles.ts
> +export const AlertContainer = styled.div`
en el sistema de diseño existe un componente`<Text />` , validar porqué con esto se ahorrarían bastante código css

2024-07-09 13:32 UTC, Andresbl123 commented on src/components/ErrorAlert/index.tsx
> +const ErrorAlert = ({ errorKey, message, onClose }: ErrorAlertProps) => {
esta parte la podemos dejar como se esta manejando en el proyecto, realizando la desestructuración dentro de la función y no en los parámetros, ejem: 
![image](https://github.com/selsa-inube/crediboard/assets/74839801/03c6ad0f-d8d8-4c69-8de2-129096ce1754)

2024-07-09 14:10 UTC, Angelbt12 commented on src/components/ErrorAlert/styles.ts
> +export const AlertContainer = styled.div`
ok

2024-07-09 14:15 UTC, Angelbt12 commented on src/components/ErrorAlert/index.tsx
> +  errorKey: boolean;
ok

2024-07-09 14:18 UTC, Angelbt12 commented on src/components/ErrorAlert/index.tsx
> +  const [visible, setVisible] = useState(errorKey);
ok

2024-07-09 14:18 UTC, Angelbt12 commented on src/components/ErrorAlert/index.tsx
> +    <AlertContainer style={{ display: visible ? "flex" : "none" }}>
ok

2024-07-09 16:19 UTC, Angelbt12 commented on src/components/ErrorAlert/index.tsx
> +export default ErrorAlert;
ok

2024-07-09 16:19 UTC, Angelbt12 commented on src/components/ErrorAlert/index.tsx
> +export default ErrorAlert;
ok

2024-07-09 16:39 UTC, Angelbt12 commented on src/components/ErrorAlert/index.tsx
> +const ErrorAlert = ({ errorKey, message, onClose }: ErrorAlertProps) => {
ok vale muchas gracias

2024-07-09 16:44 UTC, Angelbt12 commented on src/components/ErrorAlert/index.tsx
> +  const [visible, setVisible] = useState(errorKey);
ok

2024-07-09 16:44 UTC, Angelbt12 commented on src/components/ErrorAlert/index.tsx
> +  const handleClose = () => {
ok

2024-07-10 13:39 UTC, Andresbl123 commented on src/components/ErrorAlert/index.tsx
> +  const handleClose = () => {
esto se debería eliminar, desde mi punto de vita, ya que este no es un componente que se vaya a renderizar por medio de un `map` o algo así, no veo la necesidad que tenga si propio estado, de esto se podría encargar el componente padre , esto implicaría la eliminación del código de la línea 14

2024-07-11 14:04 UTC, Andresbl123 commented on src/components/ErrorAlert/styles.ts
> +  top: 62px;
estos estilos `top: 62px;  left: 0;  right: 0;` me parece que siguiendo la lógica del comentarios del componente padre, es el quien debe decidir donde o en que parte renderizar el compoente, por que si no este queda con un pocisionamiento difícil de controlar para la versión móvil, ejem: figma 
![image](https://github.com/selsa-inube/crediboard/assets/74839801/f7d323dc-bf0a-431b-903d-929d730105e9)
actual: 
![image](https://github.com/selsa-inube/crediboard/assets/74839801/6c3f488b-0704-4171-bd65-d74042937a8c)
 y aunque es verdad que la versión móvil, esta en revisión, si dejamos estos estilos por defecto se vuelve tedioso

2024-07-11 17:10 UTC, Angelbt12 commented on src/pages/board/outlets/financialReporting/index.tsx
> +  const [errorVisible, setErrorVisible] = useState(false);
ok

2024-07-11 17:19 UTC, Angelbt12 commented on src/components/ErrorAlert/styles.ts
> +  display: ${({ $visible }) => ($visible ? "flex" : "none")};
ok

2024-07-11 19:01 UTC, Angelbt12 commented on src/components/ErrorAlert/styles.ts
> +  top: 62px;
ok

2024-07-12 14:35 UTC, Andresbl123 commented on src/components/ErrorAlert/index.tsx
> +    <AlertContainer $visible={true} $top={top} $left={left}>
Eliminar esta props, ya no es necesaria `$visible={true}`

2024-07-12 14:35 UTC, Andresbl123 commented on src/components/ErrorAlert/index.tsx
Ajustar la versión móvil, para esto actualizar con la rama main

![image](https://github.com/user-attachments/assets/9c3716a1-668d-4470-89a3-d87a4801173e)

2024-07-12 14:35 UTC, Andresbl123 commented on src/components/ErrorAlert/styles.ts
> +  font-weight: 500;
esta propiedad css, tampoco es necesaria, ya lo tiene `<Text />`

2024-07-15 13:05 UTC, Angelbt12 commented on src/components/ErrorAlert/styles.ts
> +  font-weight: 500;
ok

2024-07-15 22:06 UTC, Andresbl123 approved these changes

2024-07-17 12:25 UTC, carin91 requested changes

2024-07-17 12:25 UTC, carin91 commented on src/components/ErrorAlert/index.tsx
> +  message?: string;
Include a boolean prop which will be loaded from financialReporting which indicates if the error message should be rendered for this particular credit-request.

2024-07-17 12:25 UTC, carin91 commented on src/components/ErrorAlert/index.tsx
> +      <AlertText>{message || "Existe un error sin evaluar"}</AlertText>
All of the text should be loaded from a config file, create a config file which contains "Existe un error sin evaluar" and pass it here.

2024-07-17 12:25 UTC, carin91 commented on src/components/ErrorAlert/index.tsx
> +import { Icon } from "@inubekit/icon";
You are breaking the mockups, look at the CB-102, the top 5 cards should be rendered without scrolling
Invalid
![image](https://github.com/user-attachments/assets/b6a1de5d-fb20-4748-a62c-ed22f5b36db4)

Expected:
![image](https://github.com/user-attachments/assets/cef02985-e219-471f-b99b-e64f73fadecf)

2024-07-17 18:06 UTC, Angelbt12 commented on src/components/ErrorAlert/index.tsx
> +import { Icon } from "@inubekit/icon";
ok

2024-07-17 18:18 UTC, Angelbt12 commented on src/components/ErrorAlert/index.tsx
> +  message?: string;
ok

2024-07-17 18:21 UTC, Angelbt12 commented on src/components/ErrorAlert/index.tsx
> +      <AlertText>{message || "Existe un error sin evaluar"}</AlertText>
ok

2024-07-19 12:13 UTC, closed without merging