Implement the functionality to display the modal "Adjuntar"
selsa-inube/crediboard pull request #58
Opened 2024-07-08 18:12 UTC by Andresbl123

Implement the functionality to display the modal on the attach `Button` on the `Application` page, this PR does not include the functionality of the modal to add or attach a new file. 

![image](https://github.com/selsa-inube/crediboard/assets/74839801/03170e73-f79b-4e84-b2ed-d8db2e447504)

2024-07-11 20:56 UTC, Angelbt12 reviewed
good job

2024-07-17 12:56 UTC, carin91 requested changes

2024-07-17 12:56 UTC, carin91 commented on src/components/modals/Listmodal/index.tsx
>  export const Listmodal = (props: IListmodalProps) => {
Adjust the modal to align centers between the Text and the X icon
![image](https://github.com/user-attachments/assets/61782dbb-2f7c-4661-b361-6530fc77ba40)

2024-07-17 12:56 UTC, carin91 commented on src/components/modals/Listmodal/index.tsx
> -  const { title, portalId, content, handleClose } = props;
i'm not sure about the expected behavior on "Cerrar", it should not be clickable?
![image](https://github.com/user-attachments/assets/bfba6ce3-ff49-49bc-adf3-0e7926c113a2)

2024-07-17 19:48 UTC, Andresbl123 commented on src/components/modals/Listmodal/index.tsx
>  export const Listmodal = (props: IListmodalProps) => {
resolve

2024-07-17 19:57 UTC, Andresbl123 commented on src/components/modals/Listmodal/index.tsx
> -  const { title, portalId, content, handleClose } = props;
tener en cuenta que el componente `<Stack />` no tiene ejecuta el evento `onClick`.

Resolve

2024-07-18 20:10 UTC, carin91 approved these changes

2024-07-18 20:12 UTC, carin91 approved these changes

2024-07-18 20:14 UTC, merged