Mobile version of Credit Profile
selsa-inube/crediboard pull request #59
Opened 2024-07-09 06:44 UTC by novadeveloper14

2024-07-09 15:17 UTC, Andresbl123 commented on src/pages/board/outlets/creditProfileInfo/index.tsx
> +  const isTablet = useMediaQuery("(max-width: 1200px)");
aquí como sugerencia, si es posible,  creo que sería mejor usar el custom hook `useMediaQueries` y se realiza la desestructuración con alias o algo así

2024-07-09 15:17 UTC, Andresbl123 commented on src/pages/board/outlets/creditProfileInfo/index.tsx
No se di dentro de esta tarjeta se deben realizar estos ajustes : validar con los diseños de figma, ya que en algunas cards el layout no corresponde ejem:  
- En esta parte hay un desajuste de la alineación:
![image](https://github.com/selsa-inube/crediboard/assets/74839801/692271a6-1b80-401a-9470-71e81aded1db)
- Esto se debe ajustar sin saltos de línea, y se debe ajustar la alineación: 
![image](https://github.com/selsa-inube/crediboard/assets/74839801/ed1cc176-2f4e-417a-a6d6-e37cdb1593aa)

2024-07-11 15:35 UTC, Andresbl123 commented on src/pages/board/outlets/creditProfileInfo/index.tsx
validar layout, se esta generando scroll y otros ajustes.
![image](https://github.com/selsa-inube/crediboard/assets/74839801/72c14c2c-93ac-40bc-b8df-b3470462ff96)
![image](https://github.com/selsa-inube/crediboard/assets/74839801/19b52c2d-587e-4d56-bacc-6b0fd47cc464)

2024-07-11 21:11 UTC, Andresbl123 approved these changes

2024-07-17 12:48 UTC, carin91 requested changes

2024-07-17 12:48 UTC, carin91 commented on src/pages/board/outlets/creditProfileInfo/index.tsx
>        <Grid
Adjust the behavior on tablet, it is expected that the white space filled with the next card. I'll suggest that you should just 1 grid for all of the 6 fieldsets or a flex with wrap

![image](https://github.com/user-attachments/assets/5dd08bd2-2fa7-43a5-a62e-ae6aaf553687)

2024-07-17 12:48 UTC, carin91 commented on src/pages/board/outlets/creditProfileInfo/index.tsx
> +    <Stack direction="column">
Adjust the max width of the general container on credit-profile to fit on 1440px as done in the extended-card on the cb102

2024-07-17 12:48 UTC, carin91 commented on src/pages/board/outlets/creditProfileInfo/index.tsx
> -        templateColumns="repeat(auto-fit, minmax(350px, 1fr))"
It is expected that the fieldsets adjust its height based on (1) auto for its content (2) the height of the grid track. Add to it, the height of the grid track should be calculated based on the highest fieldset.

2024-07-19 09:40 UTC, merged