cb 84 implement the reenviar use case
selsa-inube/crediboard pull request #61
Opened 2024-07-10 18:43 UTC by Angelbt12

The resend component of the Promissory Notes and Bills part is created, which looks like this:
![image](https://github.com/selsa-inube/crediboard/assets/125980817/14551cdd-7b65-49be-a374-a252691a2380)

2024-07-12 15:46 UTC, Andresbl123 commented on src/components/modals/PromissoryNotesModal/index.tsx
> +    field2: Yup.string().required("Este campo es obligatorio"),
para mi estas validaciones en la de teléfono y Whatsapp deberían validar si son number

2024-07-12 15:46 UTC, Andresbl123 commented on src/components/modals/PromissoryNotesModal/index.tsx
> +  const isMobile = useMediaQuery("(max-width: 700px)");
dejemos esta declaración después del `if`

2024-07-12 15:46 UTC, Andresbl123 commented on src/components/modals/PromissoryNotesModal/index.tsx
> +            <MdClear size={24} cursor="pointer" onClick={onCloseModal} />
Utilicemos el componente `<Icon />`

2024-07-12 15:46 UTC, Andresbl123 commented on src/components/modals/PromissoryNotesModal/index.tsx
> +  const validationSchema = Yup.object().shape({
creería que esta función se puede sacar fuera de la función del componente, validemos esto, ya que no es necesario que se renderice cada vez que lo haga el componente

2024-07-12 15:46 UTC, Andresbl123 commented on src/components/modals/PromissoryNotesModal/index.tsx
> +                      {...field}
evitemos esto y utilicemos los valores que vienen en el objeto `field `

2024-07-12 15:46 UTC, Andresbl123 commented on src/components/modals/PromissoryNotesModal/index.tsx
> +                      {...field}
tener en cuenta el comentario sobre esto

2024-07-12 15:46 UTC, Andresbl123 commented on src/components/modals/PromissoryNotesModal/styles.ts
> +  theme?: typeof inube;
`theme` no es necesario aquí, ya que es algo que nos proporciona `styled-components`

2024-07-12 22:07 UTC, Angelbt12 commented on src/components/modals/PromissoryNotesModal/index.tsx
> +    field2: Yup.string().required("Este campo es obligatorio"),
ok

2024-07-12 22:08 UTC, Angelbt12 commented on src/components/modals/PromissoryNotesModal/index.tsx
> +  const isMobile = useMediaQuery("(max-width: 700px)");
ok

2024-07-12 22:10 UTC, Angelbt12 commented on src/components/modals/PromissoryNotesModal/index.tsx
> +            <MdClear size={24} cursor="pointer" onClick={onCloseModal} />
ok

2024-07-12 22:13 UTC, Angelbt12 commented on src/components/modals/PromissoryNotesModal/index.tsx
> +  const validationSchema = Yup.object().shape({
ok

2024-07-12 22:16 UTC, Angelbt12 commented on src/components/modals/PromissoryNotesModal/index.tsx
> +                      {...field}
ok

2024-07-12 22:17 UTC, Angelbt12 commented on src/components/modals/PromissoryNotesModal/styles.ts
> +  theme?: typeof inube;
ok

2024-07-16 15:45 UTC, Andresbl123 commented
por favor resolver conflictos, porque esta rama no esta actualizada con main

2024-07-16 17:49 UTC, Angelbt12 commented on src/components/modals/PromissoryNotesModal/index.tsx
> +                      {...field}
ok

2024-07-17 16:00 UTC, Andresbl123 commented on src/components/modals/PromissoryNotesModal/index.tsx
> +const validationSchema = Yup.object().shape({
sin corregir

2024-07-17 16:00 UTC, Andresbl123 commented on src/components/modals/PromissoryNotesModal/index.tsx
> +                        <Icon
aquí no hay necesidad de pasa el componente `<Icon />` , `<Textfield />`, ya lo usa internamente, aplica para todos

2024-07-17 16:00 UTC, Andresbl123 commented on src/pages/board/outlets/financialReporting/PromissoryNotes/index.tsx
> +          actions={actionsFinanacialReporting.map(action => ({
Pienso, que esto es demasiado complicado, y esto se debe manejar desde el archivo `config,tsx`, creo qiue se puede validar desde las `actions` que recibe la tabla, desde hay se podría validar para generar una función que pueda activar el modal, lo mima para móvil, desde las `actionsMobile`, porque como esta es algo complicado de leer, enternder y mas porque es algo que se pasa como props

2024-07-17 22:18 UTC, Angelbt12 commented on src/components/modals/PromissoryNotesModal/index.tsx
> +const validationSchema = Yup.object().shape({
ok

2024-07-17 22:23 UTC, Angelbt12 commented on src/components/modals/PromissoryNotesModal/index.tsx
> +                        <Icon
ok

2024-07-17 22:52 UTC, Angelbt12 commented on src/pages/board/outlets/financialReporting/PromissoryNotes/index.tsx
> +          actions={actionsFinanacialReporting.map(action => ({
ok

2024-07-18 16:06 UTC, Andresbl123 commented on src/pages/board/outlets/financialReporting/PromissoryNotes/index.tsx
> +  const tableBoardActions = actionsFinanacialReporting.map((action) => ({
creería que esto debería ir  en el archivo de config

2024-07-18 16:06 UTC, Andresbl123 commented on src/pages/board/outlets/financialReporting/PromissoryNotes/index.tsx
> +  const tableBoardActionMobile = actionMobile.map((action) => ({
creería que esto debería ir  en el archivo de config

2024-07-18 17:15 UTC, Angelbt12 commented on src/pages/board/outlets/financialReporting/PromissoryNotes/index.tsx
> +  const tableBoardActions = actionsFinanacialReporting.map((action) => ({
ok

2024-07-22 16:16 UTC, Andresbl123 approved these changes

2024-07-22 16:16 UTC, Andresbl123 commented on src/pages/board/outlets/financialReporting/PromissoryNotes/index.tsx
> +    console.log(data);
no hay necesidad de este console.log, eliminar con eso, ya no es necesario a la función `entrySelection` y donde se utilice se manda directo `() =>  setShowModal(true)`

2024-07-22 16:16 UTC, Andresbl123 commented on src/pages/board/outlets/financialReporting/PromissoryNotes/index.tsx
> +  const handleCloseModal = () => {
se puede eliminar esta función y pasar directamente `() => setShowModal(false)`

2024-07-23 18:07 UTC, carin91 requested changes
Adjust the modal:
![image](https://github.com/user-attachments/assets/21073722-66b1-4ce0-a243-2f99bfcfbf95)
(1) Adjust the "X" to center it with the "Cerrar" text.
(2) Adjust the behavior of the modal to close by clicking on a container which contain "Cerrar" and "X"
(3) The title of the modal will be: "Confirme los datos del usuario"
(4) The contact information fields are not directly editable, the app present these fields for confirmation, however, they are not editable.
(5) Change the text on the button to "Enviar"
(6) Implement the Render message by clicking "Enviar"

2024-07-24 00:58 UTC, closed without merging