CB-87 implementation of render Message to cancel
selsa-inube/crediboard pull request #63
Opened 2024-07-12 14:42 UTC by Angelbt12

implementation of renderMessage to the override part
![image](https://github.com/user-attachments/assets/598854c4-4566-41a3-a286-4913a5624027)

2024-07-15 21:37 UTC, Andresbl123 reviewed
Validar lo hablado en la reunión, y validar los conflictos en los archivos de configuración `package-lock.json`
`package.json`

2024-07-17 16:32 UTC, Andresbl123 commented on src/components/layout/ContainerSections/index.tsx
> +const Listdata: React.FC<IListdataProps> = ({ data }) => (
Tengamos en cuenta la forma estándar del proyecto tipar la props

2024-07-17 16:32 UTC, Andresbl123 commented on src/components/layout/ContainerSections/index.tsx
> +  const handleConfirmCancel = () => {
no entiendo muy bien esta función, pero aquí hay un error de lógica, porqué, esto siempre va entrar a la primara condicional ya que `isSuccess`, esta definido en `true`

2024-07-17 16:32 UTC, Andresbl123 commented on src/components/layout/ContainerSections/styles.ts
> +  z-index: 2;
podemos quitar este z-index

2024-07-17 16:32 UTC, Andresbl123 commented on src/components/modals/TextAreaModal/index.tsx
El cambio en este archivo por qué se realiza?

2024-07-17 19:10 UTC, Angelbt12 commented on src/components/layout/ContainerSections/index.tsx
> +const Listdata: React.FC<IListdataProps> = ({ data }) => (
ok

2024-07-17 19:15 UTC, Angelbt12 commented on src/components/modals/TextAreaModal/index.tsx
ok

2024-07-18 13:04 UTC, Angelbt12 commented on src/components/layout/ContainerSections/index.tsx
> +  const handleConfirmCancel = () => {
ok

2024-07-18 15:10 UTC, Andresbl123 commented on src/components/layout/ContainerSections/index.tsx
si analizamos, esto podría tener otra perspectiva, en donde no necesite hacer ningún cambio en este archivo, ya tiene demasiada complejidad para un contenedor, así que sugiero. en este archivo no se realiza ninguna modificación, y en loque se debe trabajar es en el archivo `src/pages/board/outlets/financialReporting/index.tsx` , en este archivo se realiza la importación del `Flag` y se maneja desde ahi, ejemplo de como quedaria desde `financialReporting`:  
![image](https://github.com/user-attachments/assets/830864ea-aefc-4c1f-9ece-4264eeb678ce)

2024-07-18 15:10 UTC, Andresbl123 commented on src/components/layout/ContainerSections/styles.ts
> +export const StyledMessageContainer = styled.div`
tener en cuenta que este contenedor sería necesario , para la recomendación que doy

2024-07-21 20:01 UTC, Angelbt12 commented on src/components/layout/ContainerSections/index.tsx
ok

2024-07-21 20:01 UTC, Angelbt12 commented on src/components/layout/ContainerSections/styles.ts
> +export const StyledMessageContainer = styled.div`
ok

2024-07-22 16:55 UTC, Andresbl123 commented on src/components/layout/ContainerSections/styles.ts
> +export const StyledMessageContainer = styled.div`
Borrar esto, que no se utiliza, ya esta en `<FinancialReporting />`

2024-07-22 16:55 UTC, Andresbl123 commented on src/pages/board/outlets/financialReporting/index.tsx
> +  const handleCancelModal = () => {
evitemos esta función y pasemos donde se utiliza `() => setShowCancelModal(!showCancelModal)`

2024-07-22 16:55 UTC, Andresbl123 commented on src/pages/board/outlets/financialReporting/index.tsx
> +  const handleConfirmCancel = (values: { textarea: string }) => {
Esto lo podemos sacar fuera del componente y lo que necesite lo reciba como parámetro

2024-07-22 16:55 UTC, Andresbl123 commented on src/pages/board/outlets/financialReporting/index.tsx
> +    console.log("Flag Message:", flagMessage);
evitemos `console.log()` innecesarios

2024-07-22 17:14 UTC, Angelbt12 commented on src/pages/board/outlets/financialReporting/index.tsx
> +  const handleCancelModal = () => {
ok

2024-07-22 17:23 UTC, Angelbt12 commented on src/pages/board/outlets/financialReporting/index.tsx
> +  const handleConfirmCancel = (values: { textarea: string }) => {
ok

2024-07-22 17:24 UTC, Angelbt12 commented on src/pages/board/outlets/financialReporting/index.tsx
> +    console.log("Flag Message:", flagMessage);
ok

2024-07-23 14:16 UTC, Andresbl123 commented on package.json
> +    "@inubekit/sectionmessage": "^5.0.0",
esto esta deprecado, por favor desinstalar 
![image](https://github.com/user-attachments/assets/1e910e9a-6c7d-49fb-bccb-7376fd9b204d)

2024-07-23 14:33 UTC, Angelbt12 commented on package.json
> +    "@inubekit/sectionmessage": "^5.0.0",
ok

2024-07-23 14:36 UTC, Angelbt12 commented on src/pages/board/outlets/financialReporting/config.tsx
> +    setFlagMessage: React.Dispatch<React.SetStateAction<{ title: string; description: string; appearance: "success" | "danger" }>>,
ok

2024-07-23 15:03 UTC, Andresbl123 approved these changes

2024-07-23 17:50 UTC, carin91 requested changes

2024-07-23 17:50 UTC, carin91 commented on package-lock.json
> +    "node_modules/@rollup/rollup-android-arm-eabi": {
Delete this update on the package-lock

2024-07-24 00:34 UTC, closed without merging