Implement min-height on managment
selsa-inube/crediboard pull request #64
Opened 2024-07-15 15:34 UTC by Brandonz07

2024-07-15 21:57 UTC, Andresbl123 commented on src/pages/board/outlets/financialReporting/management/styles.ts
> +  @media (max-width: 768px) {
me parece que este componente styled-component , no es para nada necesario es decir, nos podemos ahorrar todo este código , y en el archivo  `index.tsx` podemos usar el componente `Stack `del design-system, que acepta por props todas estas configuraciones y la altura la podemos definir por medio del custom hooks `useMediaQuery` también del esign-system

2024-07-16 18:49 UTC, Brandonz07 commented on src/pages/board/outlets/financialReporting/management/styles.ts
> +  @media (max-width: 768px) {
al momento de realizar el chat no se tomo en cuenta el uso del componente, pero ya quedo

2024-07-17 16:37 UTC, Andresbl123 reviewed
cumple requerimientos

2024-07-18 20:20 UTC, carin91 requested changes

2024-07-18 20:20 UTC, carin91 commented on src/pages/board/outlets/financialReporting/management/index.tsx
> +      <Stack direction="column"  height={!isMobile ? "100%" : "292px"}>
You must guarantee the conditions on the mockups
![image](https://github.com/user-attachments/assets/27bebf77-9605-4003-8a56-85cd28038267)

2024-07-19 14:49 UTC, Brandonz07 commented on src/pages/board/outlets/financialReporting/management/index.tsx
> +      <Stack direction="column"  height={!isMobile ? "100%" : "292px"}>
They have the same size, the height of the "stack" is the same in both, which is 328px, the one that changes is when it is seen with the "title", but this is like this on all the cards due to the margin

![image](https://github.com/user-attachments/assets/93ef9e4b-7747-462a-85c0-d6663252c57b)

2024-07-23 18:28 UTC, carin91 requested changes
Resolve conflicts with main - Verify the function of the Managment Container

2024-07-24 00:55 UTC, carin91 approved these changes

2024-07-24 00:55 UTC, merged