Create mock `trace` identity
selsa-inube/crediboard pull request #65
Opened 2024-07-15 21:12 UTC by Andresbl123

the mock, of the trace identity, is created, and a test of how this is consumed is implemented in the Management section, so that the traceability is there.  

![image](https://github.com/user-attachments/assets/8623c361-1efb-4e9c-ad7b-21c70c1fc98c)

2024-07-17 06:46 UTC, novadeveloper14 approved these changes

2024-07-17 13:25 UTC, carin91 requested changes

2024-07-17 13:25 UTC, carin91 commented on src/mocks/trace/trace.mock.ts
> +      read_novelty: "new",
It could be null.
It is "N" if the message/document was sent by the client and not read by any user. Therefore, it could take "Y" or "N" if the trace_type is a novelty or a novelty_document
It is "Y" if the message/document was sent by the client but read by at least 1 user. Therefore, it could take "Y" or "N" if the trace_type is a novelty or a novelty_document
It is null if this is a message from the user, is a document by the user or it is an executed task.

2024-07-17 13:25 UTC, carin91 commented on src/mocks/trace/trace.mock.ts
> +  trace: [
Adjust the mocks based on the latest version of the entity.
![image](https://github.com/user-attachments/assets/e9fcae85-b76d-4409-98b6-90ab7aab579a)

2024-07-17 13:25 UTC, carin91 commented on src/mocks/trace/trace.mock.ts
> +      credit_request_id: "999990",
Create several traces for this credit_request

2024-07-17 13:25 UTC, carin91 commented on src/mocks/trace/trace.mock.ts
> +      trace_type: true,
Adjust all of the trace_types
![image](https://github.com/user-attachments/assets/1d5f5eea-823a-4eb7-9774-7b32528f855f)

2024-07-17 20:18 UTC, Andresbl123 commented on src/mocks/trace/trace.mock.ts
> +      read_novelty: "new",
resolve

2024-07-17 20:18 UTC, Andresbl123 commented on src/mocks/trace/trace.mock.ts
> +  trace: [
resolve

2024-07-17 20:19 UTC, Andresbl123 commented on src/mocks/trace/trace.mock.ts
> +      trace_type: true,
resolve

2024-07-17 22:56 UTC, Andresbl123 commented on src/mocks/trace/trace.mock.ts
> +      credit_request_id: "999990",
resolve

2024-07-18 20:46 UTC, carin91 approved these changes

2024-07-18 20:46 UTC, merged