Adjust the responsiveness of the board
selsa-inube/crediboard pull request #66
Opened 2024-07-15 21:52 UTC by Brandonz07

2024-07-17 06:53 UTC, novadeveloper14 requested changes

2024-07-17 06:53 UTC, novadeveloper14 commented on src/pages/board/outlets/boardlayout/styles.ts
In the mobile version the table should occupy the entire width

![image](https://github.com/user-attachments/assets/48119725-d14f-40b2-b519-e0561c2f1211)

like this

![image](https://github.com/user-attachments/assets/5f945977-b495-4ec7-8741-1df3aca3ec32)

2024-07-17 06:53 UTC, novadeveloper14 commented on src/pages/board/outlets/boardlayout/styles.ts
When using this functionality the table should occupy all 1440px

![image](https://github.com/user-attachments/assets/9688fafe-7ea1-4325-9810-c291ea7801d2)

2024-07-17 06:53 UTC, novadeveloper14 commented on src/pages/board/outlets/boardlayout/styles.ts
If this functionality is used the size of the table is changing and this should not happen

![image](https://github.com/user-attachments/assets/af3af260-e632-4562-8adc-5114b273fa89)

2024-07-17 21:32 UTC, Brandonz07 commented on src/pages/board/outlets/boardlayout/styles.ts
Using the styled, the errors are solved

2024-07-19 07:12 UTC, novadeveloper14 approved these changes

2024-07-19 09:37 UTC, carin91 approved these changes

2024-07-19 09:37 UTC, merged