Create mock `aprovals`
selsa-inube/crediboard pull request #67
Opened 2024-07-16 23:18 UTC by Andresbl123

the `approval_by_credit_request_identity` mock is created, and a test of how it is consumed is implemented in the Approvals section, so that traceability is there.

![image](https://github.com/user-attachments/assets/c303059a-348b-4ebd-a7a0-09367fd9f41c)

2024-07-19 18:06 UTC, Brandonz07 approved these changes

2024-07-26 02:30 UTC, carin91 requested changes

2024-07-26 02:30 UTC, carin91 commented on src/pages/board/outlets/financialReporting/Approvals/index.tsx
> +import { approval_by_credit_request_Mock } from "@mocks/financialReporting/Approvals";
you should not import the mocks, base the rendering of the table on the approvals service

2024-07-26 02:30 UTC, carin91 commented on src/pages/board/outlets/financialReporting/Approvals/index.tsx
> +    get<typeof approval_by_credit_request_Mock>("approval").then((data) => {
I would create an interface for the credit request. Remember that everything related to the mocks will be deleted for production.

2024-07-26 15:48 UTC, Andresbl123 commented on src/mocks/financialReporting/Approvals.ts
> +    credit_request_id: "e6b54a96-52bf-4b52-b8ce-b5870fe7a32d",
resolved


Please note that as there is no indication yet on how to handle when no data is found or when there is an error, for now it is left blank, so that in a next PR it can be solved when it is defined.

2024-07-26 15:48 UTC, Andresbl123 commented on src/pages/board/outlets/financialReporting/Approvals/index.tsx
> +import { approval_by_credit_request_Mock } from "@mocks/financialReporting/Approvals";
resolve

2024-07-26 15:48 UTC, Andresbl123 commented on src/pages/board/outlets/financialReporting/Approvals/index.tsx
> +    get<typeof approval_by_credit_request_Mock>("approval").then((data) => {
resolve

2024-07-26 15:48 UTC, Andresbl123 commented on src/mocks/financialReporting/Approvals.ts
> +    approval_id: 1,
resolve

2024-07-29 20:11 UTC, carin91 commented on src/pages/board/outlets/financialReporting/Approvals/index.tsx
> +import { approval_by_credit_request_Mock } from "@mocks/financialReporting/Approvals";
Relocate the type to the service folder.

![Uploading image.png…]()

2024-07-29 20:12 UTC, carin91 approved these changes

2024-07-30 01:59 UTC, Andresbl123 commented on src/pages/board/outlets/financialReporting/Approvals/index.tsx
> +import { approval_by_credit_request_Mock } from "@mocks/financialReporting/Approvals";
resuelto

2024-07-30 01:59 UTC, merged