At/cb 97 adjust the operation for the burger menu
selsa-inube/crediboard pull request #73
Opened 2024-07-22 17:06 UTC by Angelbt12

Implementation of the drop-down menu to show the options in the mobile format
![image](https://github.com/user-attachments/assets/b1a36fb5-4116-46fe-8d31-0126d132798b)
![image](https://github.com/user-attachments/assets/91c5d655-8a3e-4c94-8fcd-0f5d9a956ed7)

2024-07-23 22:26 UTC, novadeveloper14 commented
let's make the hamburger menu icon appear before the buttons go into the back button space

![image](https://github.com/user-attachments/assets/c62da88d-9c0d-4be2-b86e-88db1dcfc12e)

2024-07-23 22:46 UTC, novadeveloper14 requested changes

2024-07-23 22:46 UTC, novadeveloper14 commented on src/components/modals/MenuComponent/MenuComponent.tsx
> +import {
The import format that we are using in inube team is the following:

external imports
----- space
aliased internal imports
-----space 
internal imports without aliases

so in that component it should look like this:

import React from "react";
import { Text } from "@inube/design-system";
import { Icon } from "@inubekit/icon";
import { MdClose } from "react-icons/md";

import {StyledMenu,
  StyledMenuHeader,
  StyledCloseIcon,
  StyledMenuItem,
} from "./MenuComponentStyles";

if necessary please adjust this in other files

2024-07-23 22:46 UTC, novadeveloper14 commented on src/components/modals/MenuComponent/MenuComponentStyles.ts
This file should be called just styles.ts

2024-07-23 22:46 UTC, novadeveloper14 commented on src/components/modals/MenuComponent/MenuComponent.tsx
Let's rename this component as MobileMenu since the current name does not speak very well of the use that is going to be given to the component

2024-07-23 22:46 UTC, novadeveloper14 commented on src/components/modals/MenuComponent/MenuComponent.tsx
> +const MenuComponent: React.FC<MenuComponentProps> = ({
In inube we do not destructure the props, we define them inside in the following way:
```
interface TextAreaModalProps {
  title: string;
  buttonText: string;
  inputLabel: string;
  inputPlaceholder: string;
  maxLength?: number;
  portalId?: string;
  onSubmit?: (values: { textarea: string }) => void;
  onCloseModal?: () => void;
}

export function TextAreaModal(props: TextAreaModalProps) {
  const {
    title,
    buttonText,
    inputLabel,
    inputPlaceholder,
    maxLength = 200,
    portalId = "portal",
    onSubmit,
    onCloseModal,
  } = props;
  
  return(...)
  }
  
  export(TextAreaModal)
  ```

2024-07-23 22:46 UTC, novadeveloper14 commented on src/components/modals/MenuComponent/MenuComponent.tsx
> +const MenuComponent: React.FC<MenuComponentProps> = ({
the use of ReactF.C is not necessary

2024-07-23 22:46 UTC, novadeveloper14 commented on src/components/modals/MenuComponent/MenuComponent.tsx
> +const MenuComponent: React.FC<MenuComponentProps> = ({
components should be defined as function

2024-07-23 22:46 UTC, novadeveloper14 commented on src/components/layout/ContainerSections/index.tsx
> +    <ul style={{ paddingInlineStart: "2px", marginBlock: "8px" }}>
let's turn this into a styled component let's try not to put inline styles in the index

2024-07-23 22:46 UTC, novadeveloper14 commented on src/components/modals/MenuComponent/MenuComponentStyles.ts
> +  padding: 16px;
use inube.spacing.s200 
![Imagen de WhatsApp 2024-06-06 a las 11 44 41_90455e92](https://github.com/user-attachments/assets/060a427f-81f0-4ff9-82d7-8e54b3121d97)

2024-07-23 22:46 UTC, novadeveloper14 commented on src/components/modals/MenuComponent/MenuComponentStyles.ts
> +  margin-bottom: 16px;
use inube.spacing

2024-07-23 22:46 UTC, novadeveloper14 commented on src/components/modals/MenuComponent/MenuComponentStyles.ts
> +  font-size: 20px;
We should not modify font styles that should already be defined in the size and type of the Text component of the design system

2024-07-23 22:46 UTC, novadeveloper14 commented on src/components/modals/MenuComponent/MenuComponentStyles.ts
> +  font-weight: bold;
We should not modify font styles that should already be defined in the size and type of the Text component of the design system

2024-07-23 22:46 UTC, novadeveloper14 commented on src/components/modals/MenuComponent/MenuComponentStyles.ts
> +  font-size: 16px;
We should not modify font styles that should already be defined in the size and type of the Text component of the design system

2024-07-23 22:46 UTC, novadeveloper14 commented on src/components/modals/MenuComponent/MenuComponentStyles.ts
> +  cursor: pointer;
This styled component is not necessary, you should pass the cursorHover property to the Icon component and that's it:

https://github.com/selsa-inube/inubekit-icon/blob/main/src/Icon/index.tsx

2024-07-23 22:58 UTC, novadeveloper14 approved these changes

2024-07-23 22:58 UTC, novadeveloper14 commented on src/components/modals/MenuComponent/MenuComponentStyles.ts
> +  font-size: 14px;
We should not modify font styles that should already be defined in the size and type of the Text component of the design system

2024-07-23 22:58 UTC, novadeveloper14 commented on src/components/modals/MenuComponent/MenuComponent.tsx
The component should have its history in a storybook. You can follow how the TextAreaModal component was developed.

2024-07-23 22:58 UTC, novadeveloper14 commented on src/components/layout/ContainerSections/styles.ts
I am seeing that you created the same styled components that are used in the MobileMenu component and it is not using them in the index, all these styles here are irrelevant

2024-07-23 22:58 UTC, novadeveloper14 commented on src/components/modals/MenuComponent/MenuComponentStyles.ts
> +  background: white;
Whenever we pass a background to a component we should use the colors of the design system:

background-color: ${({ theme }) =>
theme?.color?.surface?.light?.clear || inube.color.surface.light.clear};

2024-07-23 22:58 UTC, novadeveloper14 commented on src/components/modals/MenuComponent/MenuComponentStyles.ts
> +export const StyledMenuHeader = styled.div`
This styled component is unnecessary to the stack component, you can pass the properties justify-content: space-between; align-items: center; also the margin-bottom: 16px; and the font-size: 20px; and font-weight: bold; They should not be used since the tokens must be passed to the Text component and this is the one in charge of setting these properties

2024-07-23 22:59 UTC, novadeveloper14 commented on src/components/modals/MenuComponent/MenuComponentStyles.ts
> +export const StyledMenuHeader = styled.div`
https://github.com/selsa-inube/design-system/blob/main/src/components/layouts/Stack/index.tsx

2024-07-23 23:00 UTC, novadeveloper14 commented
Any questions please contact teams

2024-07-24 13:33 UTC, Angelbt12 commented on src/components/modals/MenuComponent/MenuComponent.tsx
> +import {
ok

2024-07-24 13:34 UTC, Angelbt12 commented on src/components/modals/MenuComponent/MenuComponentStyles.ts
ok

2024-07-24 13:34 UTC, Angelbt12 commented on src/components/modals/MenuComponent/MenuComponent.tsx
ok

2024-07-24 14:10 UTC, Angelbt12 commented on src/components/modals/MenuComponent/MenuComponent.tsx
> +const MenuComponent: React.FC<MenuComponentProps> = ({
ok

2024-07-24 14:34 UTC, Angelbt12 commented on src/components/layout/ContainerSections/index.tsx
> +    <ul style={{ paddingInlineStart: "2px", marginBlock: "8px" }}>
ok

2024-07-24 14:51 UTC, Angelbt12 commented on src/components/modals/MenuComponent/MenuComponentStyles.ts
> +  padding: 16px;
ok

2024-07-24 15:04 UTC, Angelbt12 commented on src/components/modals/MenuComponent/MenuComponentStyles.ts
> +  margin-bottom: 16px;
ok

2024-07-24 15:16 UTC, Angelbt12 commented on src/components/modals/MenuComponent/MenuComponentStyles.ts
> +  font-size: 20px;
ok

2024-07-24 15:19 UTC, Angelbt12 commented on src/components/modals/MenuComponent/MenuComponentStyles.ts
> +  font-weight: bold;
ok

2024-07-24 15:27 UTC, Angelbt12 commented on src/components/modals/MenuComponent/MenuComponentStyles.ts
> +  font-size: 16px;
ok

2024-07-24 15:27 UTC, Angelbt12 commented on src/components/modals/MenuComponent/MenuComponentStyles.ts
> +  cursor: pointer;
ok

2024-07-24 15:28 UTC, Angelbt12 commented on src/components/modals/MenuComponent/MenuComponentStyles.ts
> +  background: white;
ok

2024-07-24 16:31 UTC, closed without merging

2024-07-24 16:52 UTC, Angelbt12 commented on src/components/modals/MenuComponent/MenuComponentStyles.ts
> +export const StyledMenuHeader = styled.div`
ok

2024-07-25 20:30 UTC, Angelbt12 commented on src/components/modals/MenuComponent/MenuComponent.tsx
ok