cb103 Implement the business unit change
selsa-inube/crediboard pull request #75
Opened 2024-07-23 13:44 UTC by Brandonz07

2024-07-24 16:37 UTC, Andresbl123 commented on src/components/layout/AppPage/index.tsx
Creo que de alguna forma sería mejor realizar la selección del de la imagen del cliente desde esta parte ya que esta implementado, por ejemplo se pueden importar las imágenes y pasarlas en la función de `rednerLogo` y dejar que `BusinessUnitChange` se encargue del cambio de cliente, por ejemplo

2024-07-24 16:37 UTC, Andresbl123 commented on src/components/layout/AppPage/index.tsx
La márgenes se descuadran en móvil, 
![image](https://github.com/user-attachments/assets/b01ceb51-7ae1-4c01-9934-acc880bb5c74)

2024-07-24 16:37 UTC, Andresbl123 commented on src/components/inputs/BusinessUnitChange/index.tsx
> +  const clients = [
pienso que esto le debe llegar por pros al componente, por lo cual pienso que se puede sacar del componente o eliminar según sea el caso

2024-07-30 15:07 UTC, Andresbl123 commented on src/components/inputs/BusinessUnitChange/styles.ts
> +export const StyledBusiness = styled.div`
validemos si se pueden desacoplar los estilos, es decir crear un styled-componentpor cada elemento html que se use y así evitar el anidamiento de estilos de ser posible

2024-07-30 15:07 UTC, Andresbl123 commented on src/components/layout/AppPage/index.tsx
> +import { Header, Grid, Icon, useMediaQuery } from "@inube/design-system";
utilizar el `<Icon />` de `@inubekit`

2024-07-30 15:07 UTC, Andresbl123 commented on src/components/layout/AppPage/index.tsx
> +import { clientsDataMock } from "@src/mocks/login/clients.mock";
cambiar a `"@mocks/login/clients.mock"`

2024-07-30 15:07 UTC, Andresbl123 commented on src/components/layout/AppPage/styles.ts
> +const StyledDivider = styled.hr`
veo que se instala el componente `@inubekit/divider`, pero no se utiliza, y aquí se crea uno, validar cual se pude utilizar y de ser necesario borrar la dependencia instalada, o este componente

2024-07-30 15:07 UTC, Andresbl123 commented on src/context/AppContext/index.tsx
> +    localStorage.setItem("clientLogo", clientLogo);
utilizar las funciones de `src/mocks/utils/dataMock.service.ts`, para acceder a la base de datos moqueada

2024-07-30 15:09 UTC, Andresbl123 commented on package.json
validar los conflictos

2024-07-31 17:12 UTC, Brandonz07 commented on src/components/inputs/BusinessUnitChange/styles.ts
> +export const StyledBusiness = styled.div`
cree varios styled components

2024-07-31 17:13 UTC, Brandonz07 commented on src/components/layout/AppPage/index.tsx
> +import { Header, Grid, Icon, useMediaQuery } from "@inube/design-system";
use el de inubekit

2024-07-31 17:26 UTC, Brandonz07 commented on src/context/AppContext/index.tsx
> +    localStorage.setItem("clientLogo", clientLogo);
estoy manejando la misma lógica que se uso en Ievent

2024-08-02 16:21 UTC, Andresbl123 commented on src/components/inputs/BusinessUnitChange/styles.ts
> +  li {
aquí propongo mal algo como esto : 
![image](https://github.com/user-attachments/assets/0f199e1b-2600-41c6-a28c-118dcbb1d20e)
![image](https://github.com/user-attachments/assets/e637f5d0-556c-41a3-a635-16f5182dc613)

2024-08-02 16:21 UTC, Andresbl123 commented on src/components/layout/AppPage/index.tsx
> +        {collapse && <StyledDivider /> && <BusinessUnitChange clients={clientsDataMock}/>}
aquí no hace falta la doble validación, es decir  `BusinessUnitChange ` no deberia depender de `StyledDivider`, debe tratarse como un todo en mi parecer, sugiero que solo dejar la validación de si viene `collapse` y utilizar un fragment de ser necesario

2024-08-05 21:31 UTC, Andresbl123 commented on src/components/inputs/BusinessUnitChange/index.tsx
> +import { Icon } from "@inube/design-system";
Utilizar el `<Icon /> del `@inubekit`, validar

2024-08-05 21:31 UTC, Andresbl123 commented on src/components/inputs/BusinessUnitChange/index.tsx
> +import { AppContext } from "@context/AppContext";
Organizar importaciones según estándar de la compañía,  primero las importaciones de terceros (librerías instaladas), y después lo que es de nuestro proyecto

2024-08-05 21:31 UTC, Andresbl123 commented on src/components/inputs/BusinessUnitChange/index.tsx
> +            <a key={client.id} href="" onClick={() => handleLogoClick(client)}>
Utilizar el componente de `<Link />` de `react-router-dom`

2024-08-05 21:31 UTC, Andresbl123 commented on src/components/inputs/BusinessUnitChange/styles.ts
> +  box-shadow: 2px 2px 3px 2px #00000040;
Los colores se deben manejar desde el sistema de diseño , en este caso desde `{ inube }  "@inube/design-system"` o si esta instalado `@inubekit/foundations`.

2024-08-05 21:31 UTC, Andresbl123 commented on src/components/inputs/BusinessUnitChange/styles.ts
> +  background-color: white;
Tener en cuenta el comentarios de los colores

2024-08-05 21:31 UTC, Andresbl123 commented on src/components/inputs/BusinessUnitChange/styles.ts
> +    theme?.color?.stroke?.divider?.regular ||
Así es como se debe definir los colores según sea el caso, para el uso de los tokens

2024-08-06 14:13 UTC, Brandonz07 commented on src/components/inputs/BusinessUnitChange/index.tsx
> +import { Icon } from "@inube/design-system";
use inubekit

2024-08-06 14:14 UTC, Brandonz07 commented on src/components/inputs/BusinessUnitChange/index.tsx
> +            <a key={client.id} href="" onClick={() => handleLogoClick(client)}>
use router-dom

2024-08-06 14:14 UTC, Brandonz07 commented on src/components/inputs/BusinessUnitChange/styles.ts
> +  background-color: white;
use el sistema de diseño

2024-08-06 15:24 UTC, Andresbl123 approved these changes
Cumple requerimiento

2024-08-07 23:02 UTC, carin91 requested changes

2024-08-08 16:48 UTC, Brandonz07 commented on package-lock.json
return the changes

2024-08-08 16:49 UTC, Brandonz07 commented on src/components/inputs/BusinessUnitChange/index.tsx
> +                <Icon
The check only appears when the unit is selected

2024-08-13 20:00 UTC, carin91 approved these changes

2024-08-13 20:00 UTC, carin91 commented on package-lock.json
Adjust to avoid the package-lock.json variation

2024-08-14 00:04 UTC, merged