At/cb 83 implement the notify use case
selsa-inube/crediboard pull request #77
Opened 2024-07-24 00:49 UTC by Angelbt12

![image](https://github.com/user-attachments/assets/92931651-8c74-48ea-a63d-d8551757eca4)

2024-07-26 03:13 UTC, carin91 requested changes

2024-07-26 03:13 UTC, carin91 commented on src/pages/board/outlets/financialReporting/Approvals/config.tsx
> +  setShowModal: (SHOWMGGAN: boolean) => void
Validate the case for the variables, why do you use caps?

2024-07-26 12:19 UTC, Angelbt12 commented on src/components/layout/ContainerSections/index.tsx
> +import { Listmodal } from "@components/modals/Listmodal";
ok

2024-07-26 12:40 UTC, Angelbt12 commented on src/components/layout/ContainerSections/index.tsx
> +                  <Button variant="outlined">
ya valido que paso

2024-07-26 12:41 UTC, Angelbt12 commented on src/components/modals/Listmodal/index.tsx
>              <Text>Cerrar</Text>
ok

2024-07-26 13:40 UTC, Angelbt12 commented on src/components/modals/Listmodal/index.tsx
> +    buttonText = "Enviar",
ok

2024-07-26 13:43 UTC, Angelbt12 commented on src/pages/board/outlets/financialReporting/Approvals/config.tsx
> +  setShowModal: (SHOWMGGAN: boolean) => void
vale ya realizo los cambios

2024-07-29 20:34 UTC, carin91 commented on src/components/layout/ContainerSections/index.tsx
> +import { Listmodal } from "@components/modals/Listmodal";
... The name will be ListModal

2024-07-29 20:37 UTC, carin91 commented on src/components/modals/Listmodal/index.tsx
>              <Text>Cerrar</Text>
Refactor to adjust the expected behavior by closing only the "cerrar" text and the "X" icon.

![image](https://github.com/user-attachments/assets/c7d6fb0a-d0db-4709-a09c-b12ecb91335f)

The modal will be closed by clicking the green rectangle:
![image](https://github.com/user-attachments/assets/e9ed9de7-67bb-4686-9049-73fafcf66b84)

2024-07-29 20:42 UTC, carin91 commented on src/components/modals/Listmodal/index.tsx
> +    buttonText = "Enviar",
Delete the interrogation symbol on buttonText.
![image](https://github.com/user-attachments/assets/5b938648-3413-4155-9e4c-3947e7d34436)

Then, delete the default value for this non-optional input.
![image](https://github.com/user-attachments/assets/6ff8f096-d4d1-4230-92aa-be38b643d50e)

Finally, the interface should be reordered to start with non-optional props and end the list of props with optional props.
![image](https://github.com/user-attachments/assets/0a7dd2a4-6685-442c-9f03-4834b8f22aa9)

2024-07-29 20:43 UTC, carin91 commented on src/pages/board/outlets/financialReporting/Approvals/config.tsx
> +  setShowModal: (SHOWMGGAN: boolean) => void
adjust the name to a propper one.

2024-07-29 20:52 UTC, Angelbt12 commented on src/components/layout/ContainerSections/index.tsx
> +import { Listmodal } from "@components/modals/Listmodal";
ok

2024-07-29 21:22 UTC, Angelbt12 commented on src/components/modals/Listmodal/index.tsx
>              <Text>Cerrar</Text>
ok

2024-07-29 21:22 UTC, Angelbt12 commented on src/components/modals/Listmodal/index.tsx
> +    buttonText = "Enviar",
ok

2024-07-29 21:23 UTC, Angelbt12 commented on src/pages/board/outlets/financialReporting/Approvals/config.tsx
> +  setShowModal: (SHOWMGGAN: boolean) => void
perdón la idea esa usar setShowModal

2024-07-31 14:05 UTC, carin91 reviewed
(1) Delete the dependencies modifications.
![image](https://github.com/user-attachments/assets/1114b564-d0a3-49d8-b462-013777b713ae)
(2) Adjust the behavior of the modal on mobile
![image](https://github.com/user-attachments/assets/ab16bf2b-de3c-428e-9542-a6f9641f19b7)

2024-07-31 22:23 UTC, carin91 approved these changes

2024-07-31 22:23 UTC, merged