At/cb 97 adjust the operation for the burger menu
selsa-inube/crediboard pull request #80
Opened 2024-07-24 17:00 UTC by Angelbt12

Implementation of the drop-down menu to show the options in the mobile format
![image](https://github.com/user-attachments/assets/b31fc5e2-952b-4f49-a971-d287459ce7d2)

2024-07-24 23:55 UTC, novadeveloper14 requested changes
conflicts need to be resolved

2024-07-25 21:10 UTC, novadeveloper14 commented
The review and comments were left in the following PR which was closed

https://github.com/selsa-inube/crediboard/pull/73

2024-07-26 06:34 UTC, novadeveloper14 requested changes

2024-07-26 06:34 UTC, novadeveloper14 commented on src/components/modals/MobileMenu/stories/MobileMenu.stories.tsx
You forgot to create the props file, which is where the component's props are described and then passed to the story's argTypes. You can use src\components\modals\TextAreaModal\stories\props.ts as a guide. To test the correct functionality of the story, you can run "npm run storybook" in the console.

2024-07-26 06:34 UTC, novadeveloper14 commented on src/components/modals/MobileMenu/styles.ts
> +  font-size: 14px;
We should not modify text styles.

2024-07-26 06:35 UTC, novadeveloper14 commented
fix conflicts

2024-07-26 18:41 UTC, Angelbt12 commented on src/components/layout/ContainerSections/index.tsx
> +import { Button, Text, inube } from "@inube/design-system";
ok

2024-07-26 18:41 UTC, Angelbt12 commented on src/components/layout/ContainerSections/index.tsx
> +import { MobileMenu } from "@src/components/modals/MobileMenu/MobileMenu";
ok

2024-07-26 23:24 UTC, Angelbt12 commented on src/components/modals/MobileMenu/stories/MobileMenu.stories.tsx
OK

2024-07-29 14:00 UTC, novadeveloper14 requested changes

2024-07-29 14:00 UTC, novadeveloper14 commented on src/components/modals/MobileMenu/stories/props.ts
> +// src/components/modals/MobileMenu/stories/props.ts
Do not leave comments in the code

2024-07-29 14:00 UTC, novadeveloper14 commented on src/components/modals/MobileMenu/MobileMenu.tsx
This file should be called index.tsx in any case in any component it should be called index.tsx and styles.ts what distinguishes the file is the name of its folder

2024-07-29 14:07 UTC, Angelbt12 commented on src/components/modals/MobileMenu/MobileMenu.tsx
ok

2024-07-29 14:07 UTC, Angelbt12 commented on src/components/modals/MobileMenu/stories/props.ts
> +// src/components/modals/MobileMenu/stories/props.ts
ok

2024-07-29 15:57 UTC, closed without merging