cb-85 Update the tags based on inubekit.
selsa-inube/crediboard pull request #82
Opened 2024-07-24 19:09 UTC by Angelbt12

tag settings in requirements
![image](https://github.com/user-attachments/assets/57c97ee6-4ec3-41ce-8a88-b618748e4635)

2024-07-24 23:50 UTC, novadeveloper14 requested changes
the component still needs to be updated in some files

![image](https://github.com/user-attachments/assets/18369a23-117b-435c-aca0-102aaf66db3c)

2024-07-24 23:50 UTC, novadeveloper14 commented
conflicts need to be resolved

2024-07-25 18:11 UTC, novadeveloper14 requested changes
need to update in:

src\components\data\TableBoard\stories\mockStories.tsx
src\pages\board\outlets\financialReporting\PromissoryNotes\config.tsx

2024-07-25 19:05 UTC, novadeveloper14 requested changes

2024-07-25 19:05 UTC, novadeveloper14 commented on src/components/data/TableBoard/stories/mockStories.tsx
> +import {Tag} from "@inubekit/tag";
This is an external export of the design system library, adjust import format

2024-07-25 19:05 UTC, novadeveloper14 commented on src/pages/board/outlets/financialReporting/PromissoryNotes/config.tsx
> +import { Tag } from "@inubekit/tag";
This is an external export of the design system library, adjust import format

2024-07-26 18:43 UTC, Angelbt12 commented on src/components/data/TableBoard/stories/mockStories.tsx
> +import {Tag} from "@inubekit/tag";
ok

2024-07-26 20:31 UTC, Angelbt12 commented on src/pages/board/outlets/financialReporting/PromissoryNotes/config.tsx
> +import { Tag } from "@inubekit/tag";
ok

2024-07-26 20:49 UTC, Angelbt12 commented on src/components/data/TableBoard/stories/mockStories.tsx
> +import {Tag} from "@inubekit/tag";
ok

2024-07-29 13:30 UTC, novadeveloper14 requested changes

2024-07-29 13:30 UTC, novadeveloper14 commented on src/components/data/TableBoard/stories/mockStories.tsx
> +import { Icon, Stack} from "@inube/design-system";
import { Icon, Stack} from "@inube/design-system";
import {Tag} from "@inubekit/tag";

These two exports are external so they should be at the top of the imports, it is not an internal import with aliases, it is an export of a module.

2024-07-29 13:30 UTC, novadeveloper14 commented on src/pages/board/outlets/financialReporting/PromissoryNotes/config.tsx
> +import { Tag } from "@inubekit/tag";
import { Icon } from "@inubekit/icon";
import { Tag } from "@inubekit/tag";

These two exports are external so they should be at the top of the imports, it is not an internal import with aliases, it is an export of a module.

2024-07-29 13:41 UTC, Angelbt12 commented on src/components/data/TableBoard/stories/mockStories.tsx
> +import { Icon, Stack} from "@inube/design-system";
ok

2024-07-29 13:41 UTC, Angelbt12 commented on src/pages/board/outlets/financialReporting/PromissoryNotes/config.tsx
> +import { Tag } from "@inubekit/tag";
ok

2024-07-29 14:14 UTC, novadeveloper14 approved these changes

2024-07-31 14:15 UTC, carin91 approved these changes

2024-07-31 14:25 UTC, merged