At/cb 99 adjust the request table to avoid scroll on mobile
selsa-inube/crediboard pull request #86
Opened 2024-07-24 21:54 UTC by Angelbt12

Adjust the requirements fieldset on mobile version to avoid the scroll
![image](https://github.com/user-attachments/assets/6131984d-529a-4120-977c-041965228c32)

2024-07-25 08:25 UTC, novadeveloper14 requested changes
The container still has internal scroll, the size of the actions has changed and does not comply with what the designs require

figma:

![image](https://github.com/user-attachments/assets/b991e746-0ab0-4a73-ba98-7ce94447e05f)

development:

![image](https://github.com/user-attachments/assets/3acc3fe0-6d86-4618-9010-c2f57916be1e)

2024-07-25 18:07 UTC, novadeveloper14 approved these changes

2024-07-26 03:22 UTC, carin91 requested changes
You are breaking the app including an additional scrollbar
![image](https://github.com/user-attachments/assets/154ec2e3-9a2c-48a9-b8e6-b3966819cac8)

2024-07-31 14:30 UTC, carin91 approved these changes

2024-07-31 14:30 UTC, merged