cb93 Create a Mock for ToDo
selsa-inube/crediboard pull request #87
Opened 2024-07-25 18:02 UTC by novadeveloper14

2024-07-27 19:48 UTC, Andresbl123 commented on src/mocks/financial-reporting/to-do/toDo.mock.ts
> +export const mockToDo: IToDo = {
Esto aconsejaría que mejor fuera un array de objetos, ya que lo que se guarda en la base da datos mockeada, es un array, con esto se evitaría medicar en cuanto a lógica a `intializedData()`, y se conserva la misma estructura de datos en la base de datos

2024-07-27 19:48 UTC, Andresbl123 commented on src/mocks/utils/dataMock.service.ts
> +export async function intializedData<T>(option: string, data: T | T[]) {
con el ajuste al mock,, ya a no sería necesario modifica esta función

2024-07-27 19:48 UTC, Andresbl123 commented on src/pages/board/outlets/financialReporting/ToDo/index.tsx
> +          commercialManager={tempStaff.commercialManager || ""}
esto no se si sea necesario, si el valor viene `falsy` podemos dejar el mismo valor que viene en el objeto

2024-07-27 19:54 UTC, Andresbl123 commented on src/pages/board/outlets/financialReporting/ToDo/index.tsx
> +    const fetchData = async () => {
Esta función se puede optimizar un poco mejor, aunque es verdad que es una función asíncrona, es una función asíncrona secuencial, es decir debo esperar la ejecución del primer `await`, para que después se ejecute el segundo, sugiero que se utilice el método `Promise.allSettled`, con eso las promesas se ejecutan al mismo tiempo en hilos distintos, un ejemplo podría ser: 
![image](https://github.com/user-attachments/assets/0c2eaf9e-f023-44f8-98c9-c217230f6ee9)

2024-07-30 21:17 UTC, Andresbl123 approved these changes

2024-07-31 14:42 UTC, carin91 requested changes

2024-07-31 14:42 UTC, carin91 commented on src/mocks/financial-reporting/to-do/toDo.mock.ts
> +    decisions: "pending",
As decisions return an array with the values reported bellow:
![image](https://github.com/user-attachments/assets/71c55dab-90d1-4b7d-ac5c-868d47d3a5c6)
With this, render the options of "Decisión" based on the mockup.
(2) Create an entry with every ID and render the information based on the ID parameter.

2024-07-31 14:42 UTC, carin91 commented on src/pages/board/outlets/financialReporting/ToDo/index.tsx
> +    commercialManager: "",
The ToDo component should verify whether the credit request has a commercial manager or not. If not, the frontend will consume a patch service to assign the Commercial Manager as the signed user.  Mock this behavior assigning a burned name and user id if you access a credit-request that has not assigned a commercial manager.

2024-08-14 02:24 UTC, carin91 approved these changes

2024-08-14 02:26 UTC, carin91 approved these changes

2024-08-14 02:26 UTC, merged