Include inputs CU001 - CU006
selsa-inube/crediboard pull request #9
Opened 2024-04-12 20:38 UTC by novadeveloper14

The board inputs were added to home as discussed in the weekly meeting, the structure was designed so that when the nav is removed it is not affected and remains the same as in figma.

![image](https://github.com/selsa-inube/crediboard/assets/87447257/e691eb09-6a0f-422d-b6d4-bf5d126be22c)

2024-04-13 01:07 UTC, Andresbl123 commented on src/pages/home/interface.tsx
> +                options={[
aquí podríamos mejor guardar las opciones en variable y pasarla, para que no quede dentro den jsx, la definiciones de las opciones

2024-04-15 14:38 UTC, Andresbl123 approved these changes
Cumple requerimiento

2024-04-16 10:45 UTC, carin91 requested changes

2024-04-18 07:31 UTC, carin91 approved these changes

2024-04-18 07:31 UTC, merged