cb110 Adjust the DB mock for trace
selsa-inube/crediboard pull request #95
Opened 2024-07-30 16:20 UTC by Brandonz07

The original version of the “chat” component in the “management” field uses a message mock to render and save the messages, however, it should render and save the messages based on the “trace” mock. Update the behavior of the chat component to do that.

This task includes the deletion of the message mock and the adjustments of the trace entity.

![image](https://github.com/user-attachments/assets/163593be-d435-4c8d-93c5-6e955ff30890)

2024-07-30 20:48 UTC, Andresbl123 commented on src/pages/board/outlets/financialReporting/management/index.tsx
> +        const trace = data.find(
esta parte no me queda muy clara, no entiendo por que solo se traer el primer elemento que coincida con el id, aquí se pierde el resto de la data asociada al cliente

2024-07-30 20:48 UTC, Andresbl123 commented on src/pages/board/outlets/financialReporting/management/index.tsx
> +  const sendMessage = async () => {
yo creo que de acuerdo ha lo hablado en la reunión esta función no es necesaria

2024-07-30 20:48 UTC, Andresbl123 commented on src/pages/board/outlets/financialReporting/management/index.tsx
> +interface TraceType {
esta interface, creo que tampoco va, y de ser necesaria una interface para `trece`, crearla en directorio de `services`

2024-08-01 15:18 UTC, Andresbl123 approved these changes

2024-08-01 21:25 UTC, carin91 requested changes

2024-08-01 21:25 UTC, carin91 commented on src/mocks/financialReporting/trace.mock.ts
> +  {
Adjust the build Data util to include an additional prop that defines whether or not the build data will include an id or not.
![image](https://github.com/user-attachments/assets/3bf930e3-d7ec-4916-befa-f490004d5208)

In the case of the trace mock, the id should not be included.

2024-08-07 23:33 UTC, carin91 commented on src/mocks/financialReporting/trace.mock.ts
> +  {
The change is pending:
![image](https://github.com/user-attachments/assets/e64dd473-c0b9-4d7a-adf1-e8ef38dda157)

2024-08-08 14:25 UTC, Brandonz07 commented on src/mocks/financialReporting/trace.mock.ts
> +  {
The trace is working correctly, try logging out

![image](https://github.com/user-attachments/assets/00262a9c-7de7-4b3c-a8db-9cf544debdc8)

2024-08-14 01:56 UTC, carin91 approved these changes

2024-08-14 13:01 UTC, merged